"""Generate our own default odds -- real projections, priced with standard vig.

This is the "(A) our own default odds file, maintained manually or
generated by our model" source. Every line here traces to the real player
pool the fantasy Quant Engine already projects (:mod:`fantasy.projections`):
a per-game rate for a real, played stat, not a fabricated number and not
anything fetched from a sportsbook. Standard -110/-110 pricing is applied
because we have no market vig to observe -- it is the conventional default
for a two-way line, not a claim about any real book's actual price.
"""

from __future__ import annotations

from typing import Any

from fantasy.projections import load_forward_projections

from .moneyline_model import fair_moneyline
from .team_model import team_scoring_averages

#: stat -> (canonical season-total field, minimum games_played to trust a rate).
_PROP_STAT_FIELDS: dict[str, str] = {
    "passing_yards": "passing_yards",
    "passing_tds": "passing_tds",
    "rushing_yards": "rushing_yards",
    "rushing_tds": "rushing_tds",
    "receiving_yards": "receiving_yards",
    "receptions": "receptions",
}

#: Which prop markets are worth offering per position -- a kicker's
#: "passing_yards" line would just be 0.0 for every kicker, which is not a
#: real market.
_MARKETS_BY_POSITION: dict[str, tuple[str, ...]] = {
    "QB": ("passing_yards", "passing_tds", "rushing_yards"),
    "RB": ("rushing_yards", "rushing_tds", "receptions", "receiving_yards"),
    "WR": ("receiving_yards", "receptions", "rushing_yards"),
    "TE": ("receiving_yards", "receptions"),
}

_DEFAULT_PRICE = -110.0
_MIN_GAMES_PLAYED = 4

#: Minimum real per-game rate before a market is offered at all, checked
#: against the *raw rate*, not the rounded line -- a rounded line is always
#: >= 0.5 by construction (see _round_to_half), so checking it can never
#: filter anything. Without this, e.g. a WR who averages 0.2 rushing
#: yards/game (a real stat, but not a real market) still gets a
#: "rushing_yards" line, and a model comparing a real 0.2-mean distribution
#: to that line reports a huge, meaningless "edge". Yardage thresholds
#: filter out a stat that isn't really part of the player's role; TD/
#: reception thresholds stay low since real books do offer longshot anytime
#: markets even at low rates.
_MIN_RATE_BY_MARKET: dict[str, float] = {
    "passing_yards": 20.0,
    "passing_tds": 0.05,
    "rushing_yards": 3.0,
    "rushing_tds": 0.05,
    "receiving_yards": 3.0,
    "receiving_tds": 0.05,
    "receptions": 0.3,
}


def _round_to_half(value: float) -> float:
    """Nearest sportsbook-style X.5 line -- never a whole number.

    A real two-way prop line always lands on a half point specifically so
    it can never push; ``round(value * 2) / 2`` doesn't guarantee that (a
    value like 0.9 rounds to 1.0, not 0.5 or 1.5). This always returns
    ``n + 0.5`` for the integer ``n`` closest to ``value - 0.5``.
    """
    return round(value - 0.5) + 0.5


def generate_default_props(
    season: int | None = None, *, top_n_per_position: int = 15
) -> list[dict[str, Any]]:
    """Real per-game-rate prop lines for the top real players at each skill position.

    Uses the same forward-projected pool (:func:`fantasy.projections.load_forward_projections`)
    the rest of the app already shows -- a player's line is their real
    season-total stat divided by real games played, rounded to a
    sportsbook-style half point. Deterministic for a given ``season``: no
    randomness, no network access.
    """
    players = load_forward_projections(season=season)
    by_position: dict[str, list[dict[str, Any]]] = {}
    for player in players:
        position = str(player.get("position") or "").upper()
        if position in _MARKETS_BY_POSITION:
            by_position.setdefault(position, []).append(player)

    rows: list[dict[str, Any]] = []
    for position, markets in _MARKETS_BY_POSITION.items():
        pool = sorted(by_position.get(position, []), key=lambda p: -float(p.get("projection") or 0.0))
        for player in pool[:top_n_per_position]:
            games = float(player.get("games_played") or player.get("prior_games_played") or 0.0)
            if games < _MIN_GAMES_PLAYED:
                continue
            for market in markets:
                field = _PROP_STAT_FIELDS[market]
                season_total = float(player.get(field) or 0.0)
                rate = season_total / games
                if rate < _MIN_RATE_BY_MARKET[market]:
                    continue
                line = _round_to_half(rate)
                rows.append(
                    {
                        "player_id": str(player.get("player_id") or ""),
                        "name": str(player.get("name") or ""),
                        "team": str(player.get("team") or "").upper(),
                        "market": market,
                        "line": line,
                        "over_price": _DEFAULT_PRICE,
                        "under_price": _DEFAULT_PRICE,
                        "basis": f"{season or 'latest'} real per-game rate ({games:g} games)",
                    }
                )
    return rows


def generate_default_games(source_season: int, *, weeks: tuple[int, ...] = (1,)) -> list[dict[str, Any]]:
    """Real upcoming games (``source_season + 1``), priced with our own fair-line model.

    Uses the real next-season schedule (who plays whom, not fabricated
    matchups) and :func:`betting.moneyline_model.fair_moneyline`, which
    itself is built on real ``source_season`` team scoring -- the same
    "next season's schedule, this season's real proxy data" convention
    :mod:`fantasy.data_loader` already uses for bye weeks and opponents.
    Total price uses standard -110/-110 (no real vig to observe); the
    moneyline is our own fair price, not additionally vigged, since it is
    explicitly the "generated by our model" default the caller can compare
    real market odds against.
    """
    try:
        import nflreadpy
    except ImportError:
        return []

    target_season = source_season + 1
    try:
        schedules = nflreadpy.load_schedules(seasons=[target_season]).to_pandas()
    except Exception:
        return []
    if schedules.empty or "game_type" not in schedules.columns:
        return []
    reg = schedules[(schedules["game_type"] == "REG") & (schedules["week"].isin(weeks))]
    if reg.empty:
        return []

    averages = team_scoring_averages(source_season)
    rows: list[dict[str, Any]] = []
    for row in reg.to_dict("records"):
        home, away, week = row.get("home_team"), row.get("away_team"), row.get("week")
        if not home or not away or week is None:
            continue
        home, away, week = str(home).strip().upper(), str(away).strip().upper(), int(week)
        fair = fair_moneyline(home, away, averages=averages)
        rows.append(
            {
                "game_id": f"{target_season}_{week:02d}_{away}_{home}",
                "week": week,
                "home_team": home,
                "away_team": away,
                "moneyline_home": fair["fair_home_moneyline"],
                "moneyline_away": fair["fair_away_moneyline"],
                "total_line": fair["total"],
                "total_over_price": _DEFAULT_PRICE,
                "total_under_price": _DEFAULT_PRICE,
                "basis": f"{target_season} real schedule, priced from {source_season} real team scoring",
            }
        )
    return rows
