"""Odds loading: our default odds.json plus user-uploaded overrides.

Two sources only, both offline:

* :func:`load_default_odds` -- our own ``odds.json`` (hand-maintained or
  generated by our fair-line models). Never fetched over the network; it is
  a local file this codebase ships or the caller points at.
* :func:`load_uploaded_odds` -- a user-supplied CSV, JSON, or delimited-text
  file (path, file-like object, or raw string), parsed offline.

:func:`merge_odds` combines them deterministically: an uploaded entry
overrides the default entry with the same key (a game id, or a player +
market pair); every other default entry passes through unchanged. Nothing
in this module ever performs a network request.
"""

from __future__ import annotations

import csv
import io
import json
from pathlib import Path
from typing import Any

DATA_ROOT = Path(__file__).resolve().parents[1] / "data"
DEFAULT_ODDS_PATH = DATA_ROOT / "odds.json"

_GAME_ID_ALIASES = ("game_id", "id", "gid")
_WEEK_ALIASES = ("week",)
_HOME_TEAM_ALIASES = ("home_team", "home")
_AWAY_TEAM_ALIASES = ("away_team", "away")
_ML_HOME_ALIASES = ("moneyline_home", "home_ml", "home_moneyline", "ml_home")
_ML_AWAY_ALIASES = ("moneyline_away", "away_ml", "away_moneyline", "ml_away")
_SPREAD_LINE_ALIASES = ("spread_home", "home_spread", "spread")
_SPREAD_HOME_PRICE_ALIASES = ("spread_home_price", "home_spread_price")
_SPREAD_AWAY_PRICE_ALIASES = ("spread_away_price", "away_spread_price")
_TOTAL_LINE_ALIASES = ("total_line", "total", "over_under")
_TOTAL_OVER_PRICE_ALIASES = ("total_over_price", "over_price_total", "total_over")
_TOTAL_UNDER_PRICE_ALIASES = ("total_under_price", "under_price_total", "total_under")

_PLAYER_ID_ALIASES = ("player_id", "id", "player")
_PLAYER_NAME_ALIASES = ("name", "player_name", "player")
_TEAM_ALIASES = ("team", "nfl_team")
_MARKET_ALIASES = ("market", "stat", "category", "prop", "prop_type")
_LINE_ALIASES = ("line", "prop_line", "value")
_OVER_PRICE_ALIASES = ("over_price", "over", "over_odds")
_UNDER_PRICE_ALIASES = ("under_price", "under", "under_odds")


class OddsLoadError(ValueError):
    """An odds source (default or uploaded) could not be parsed."""


def _empty_odds() -> dict[str, Any]:
    return {"games": {}, "player_props": {}}


def _safe_float(value: Any, default: float | None = None) -> float | None:
    if value is None or value == "":
        return default
    try:
        number = float(value)
    except (TypeError, ValueError):
        return default
    return number if number == number else default  # filter NaN


def _first(row: dict[str, Any], aliases: tuple[str, ...]) -> Any:
    for alias in aliases:
        if alias in row and row[alias] not in (None, ""):
            return row[alias]
    return None


def _normalize_game_row(row: dict[str, Any], *, source: str) -> dict[str, Any] | None:
    home = str(_first(row, _HOME_TEAM_ALIASES) or "").strip().upper()
    away = str(_first(row, _AWAY_TEAM_ALIASES) or "").strip().upper()
    game_id = str(_first(row, _GAME_ID_ALIASES) or "").strip()
    if not game_id:
        if not (home and away):
            return None
        week = _first(row, _WEEK_ALIASES)
        game_id = f"{week or 'NA'}_{away}_{home}"

    game: dict[str, Any] = {"game_id": game_id, "home_team": home, "away_team": away, "source": source}
    week = _safe_float(_first(row, _WEEK_ALIASES))
    if week is not None:
        game["week"] = int(week)

    ml_home = _safe_float(_first(row, _ML_HOME_ALIASES))
    ml_away = _safe_float(_first(row, _ML_AWAY_ALIASES))
    if ml_home is not None or ml_away is not None:
        game["moneyline"] = {"home": ml_home, "away": ml_away}

    spread_line = _safe_float(_first(row, _SPREAD_LINE_ALIASES))
    spread_home_price = _safe_float(_first(row, _SPREAD_HOME_PRICE_ALIASES), -110.0)
    spread_away_price = _safe_float(_first(row, _SPREAD_AWAY_PRICE_ALIASES), -110.0)
    if spread_line is not None:
        game["spread"] = {"home_line": spread_line, "home_price": spread_home_price, "away_price": spread_away_price}

    total_line = _safe_float(_first(row, _TOTAL_LINE_ALIASES))
    total_over_price = _safe_float(_first(row, _TOTAL_OVER_PRICE_ALIASES), -110.0)
    total_under_price = _safe_float(_first(row, _TOTAL_UNDER_PRICE_ALIASES), -110.0)
    if total_line is not None:
        game["total"] = {"line": total_line, "over_price": total_over_price, "under_price": total_under_price}

    if not any(key in game for key in ("moneyline", "spread", "total")):
        return None
    basis = row.get("basis")
    if basis:
        game["basis"] = str(basis)
    return game


def _normalize_prop_row(row: dict[str, Any], *, source: str) -> dict[str, Any] | None:
    player_id = str(_first(row, _PLAYER_ID_ALIASES) or "").strip()
    name = str(_first(row, _PLAYER_NAME_ALIASES) or "").strip()
    market = str(_first(row, _MARKET_ALIASES) or "").strip().lower().replace(" ", "_")
    line = _safe_float(_first(row, _LINE_ALIASES))
    if not (player_id or name) or not market or line is None:
        return None
    if not player_id:
        player_id = name.strip().lower().replace(" ", "_")

    prop: dict[str, Any] = {
        "player_id": player_id,
        "name": name or player_id,
        "team": str(_first(row, _TEAM_ALIASES) or "").strip().upper(),
        "market": market,
        "line": line,
        "over_price": _safe_float(_first(row, _OVER_PRICE_ALIASES), -110.0),
        "under_price": _safe_float(_first(row, _UNDER_PRICE_ALIASES), -110.0),
        "source": source,
    }
    basis = row.get("basis")
    if basis:
        prop["basis"] = str(basis)
    return prop


def _prop_key(player_id: str, market: str) -> str:
    return f"{player_id}:{market}"


def _classify_rows(rows: list[dict[str, Any]]) -> str:
    """Decide whether a batch of flat rows describes games or player props."""
    prop_signal = {*_MARKET_ALIASES, *_LINE_ALIASES, *_OVER_PRICE_ALIASES, *_UNDER_PRICE_ALIASES}
    game_signal = {
        *_ML_HOME_ALIASES,
        *_ML_AWAY_ALIASES,
        *_SPREAD_LINE_ALIASES,
        *_TOTAL_LINE_ALIASES,
        "moneyline",
        "spread",
        "total",
    }
    keys: set[str] = set()
    for row in rows[:5]:
        keys.update(str(key).strip().lower() for key in row)
    return "props" if keys & prop_signal else "games" if keys & game_signal else "props"


def _rows_from_dicts(rows: list[dict[str, Any]], *, source: str) -> dict[str, Any]:
    odds = _empty_odds()
    kind = _classify_rows(rows)
    for raw in rows:
        row = {str(key).strip().lower(): value for key, value in raw.items()}
        if kind == "games":
            game = _normalize_game_row(row, source=source)
            if game is not None:
                odds["games"][game["game_id"]] = game
        else:
            prop = _normalize_prop_row(row, source=source)
            if prop is not None:
                odds["player_props"][_prop_key(prop["player_id"], prop["market"])] = prop
    return odds


def _parse_json_payload(payload: Any, *, source: str) -> dict[str, Any]:
    if isinstance(payload, dict) and ("games" in payload or "player_props" in payload):
        odds = _empty_odds()
        for game_id, row in (payload.get("games") or {}).items():
            row = dict(row)
            row.setdefault("game_id", game_id)
            normalized = _normalize_game_row({str(k).lower(): v for k, v in row.items()}, source=source)
            if normalized is not None:
                odds["games"][normalized["game_id"]] = normalized
        raw_props = payload.get("player_props")
        prop_rows = raw_props.values() if isinstance(raw_props, dict) else (raw_props or [])
        for row in prop_rows:
            prop = _normalize_prop_row({str(k).lower(): v for k, v in dict(row).items()}, source=source)
            if prop is not None:
                odds["player_props"][_prop_key(prop["player_id"], prop["market"])] = prop
        return odds
    if isinstance(payload, list):
        return _rows_from_dicts([dict(row) for row in payload if isinstance(row, dict)], source=source)
    raise OddsLoadError("JSON odds payload must be a {'games':..., 'player_props':...} object or a list of rows")


def _sniff_delimiter(text: str) -> str:
    first_line = text.splitlines()[0] if text.splitlines() else ""
    if "\t" in first_line:
        return "\t"
    if "|" in first_line:
        return "|"
    return ","


def _parse_delimited_text(text: str, *, source: str) -> dict[str, Any]:
    delimiter = _sniff_delimiter(text)
    reader = csv.DictReader(io.StringIO(text), delimiter=delimiter)
    if reader.fieldnames is None:
        return _empty_odds()
    rows = [dict(row) for row in reader]
    return _rows_from_dicts(rows, source=source)


def load_default_odds(path: str | Path | None = None) -> dict[str, Any]:
    """Load our default odds file (JSON). Missing file -> an empty, valid odds object.

    A missing default is a normal "nothing configured yet" state, not an
    error -- :func:`unified_odds` still works from an upload alone.
    """
    target = Path(path) if path is not None else DEFAULT_ODDS_PATH
    if not target.is_file():
        return _empty_odds()
    try:
        payload = json.loads(target.read_text(encoding="utf-8-sig"))
    except (OSError, json.JSONDecodeError) as error:
        raise OddsLoadError(f"could not read default odds file {target}: {error}") from error
    return _parse_json_payload(payload, source="default")


def load_uploaded_odds(source: Any, *, file_format: str | None = None) -> dict[str, Any]:
    """Parse a user-uploaded odds file: JSON, CSV, or delimited text.

    ``source`` may be a path, a file-like object (e.g. a Streamlit
    ``UploadedFile``), raw ``str``/``bytes`` content, or already-parsed
    JSON (``dict``/``list``). ``file_format`` forces ``"json"``/``"csv"``/
    ``"text"``; omitted, the format is inferred from a file extension when
    available and otherwise by content sniffing (valid JSON parses as
    JSON; anything else is treated as delimited text, which also covers
    CSV).
    """
    if isinstance(source, (dict, list)):
        return _parse_json_payload(source, source="uploaded")

    name = ""
    if isinstance(source, (str, Path)) and not _looks_like_inline_content(source):
        path = Path(source)
        if path.is_file():
            name = path.suffix.lower()
            text = path.read_text(encoding="utf-8-sig")
        else:
            raise OddsLoadError(f"uploaded odds source does not exist: {path}")
    elif hasattr(source, "read"):
        name = Path(getattr(source, "name", "")).suffix.lower()
        raw = source.read()
        text = raw.decode("utf-8-sig") if isinstance(raw, bytes) else str(raw)
    elif isinstance(source, bytes):
        text = source.decode("utf-8-sig")
    elif isinstance(source, str):
        text = source
    else:
        raise OddsLoadError(f"unsupported uploaded odds source type: {type(source).__name__}")

    fmt = file_format or ({".json": "json", ".csv": "csv", ".tsv": "csv", ".txt": "text"}.get(name))
    if fmt is None:
        stripped = text.strip()
        fmt = "json" if stripped.startswith(("{", "[")) else "text"

    if fmt == "json":
        try:
            payload = json.loads(text)
        except json.JSONDecodeError as error:
            raise OddsLoadError(f"invalid JSON odds upload: {error}") from error
        return _parse_json_payload(payload, source="uploaded")
    return _parse_delimited_text(text, source="uploaded")


def _looks_like_inline_content(value: str | Path) -> bool:
    text = str(value)
    return ("\n" in text) or text.strip().startswith(("{", "["))


def merge_odds(default: dict[str, Any], uploaded: dict[str, Any] | None) -> dict[str, Any]:
    """Merge default odds with an uploaded override, deterministically.

    An uploaded entry overrides the default entry sharing its key (game id,
    or player+market); every other default entry passes through unchanged.
    Dict ordering is insertion order (default entries first, then any new
    keys the upload adds), so the merge is reproducible run to run.
    """
    merged: dict[str, Any] = {"games": dict(default.get("games") or {}), "player_props": dict(default.get("player_props") or {})}
    if not uploaded:
        return merged
    for game_id, game in (uploaded.get("games") or {}).items():
        merged["games"][game_id] = game
    for key, prop in (uploaded.get("player_props") or {}).items():
        merged["player_props"][key] = prop
    return merged


def unified_odds(
    *,
    default_path: str | Path | None = None,
    uploaded: Any = None,
    uploaded_format: str | None = None,
) -> dict[str, Any]:
    """Load the default odds file, optionally merge an uploaded override, and return one unified object.

    Returns ``{"games": {game_id: {...}}, "player_props": {"player_id:market": {...}}}``,
    each entry tagged ``"source": "default"`` or ``"source": "uploaded"``.
    """
    default = load_default_odds(default_path)
    if uploaded is None:
        return default
    uploaded_odds = load_uploaded_odds(uploaded, file_format=uploaded_format)
    return merge_odds(default, uploaded_odds)
