import sys
from pathlib import Path

_PROJECT_ROOT = str(Path(__file__).resolve().parents[2])
while _PROJECT_ROOT in sys.path:
    sys.path.remove(_PROJECT_ROOT)
sys.path.insert(0, _PROJECT_ROOT)
_loaded_app = sys.modules.get("app")
if _loaded_app is not None and not hasattr(_loaded_app, "__path__"):
    del sys.modules["app"]

_FANTASY_ENGINE_ROOT = Path(__file__).resolve().parents[3] / "fantasy_engine"
if _FANTASY_ENGINE_ROOT.is_dir() and str(_FANTASY_ENGINE_ROOT) not in sys.path:
    sys.path.insert(0, str(_FANTASY_ENGINE_ROOT))

# Betting Engine: offline, deterministic fair-line analysis across five
# sections -- Player Props, Money Lines, Parlays, Player Comparison, and
# Cross-Sport Parlay -- for both NFL and NBA.
#
# Odds come from exactly two places, both offline, per sport: our own
# default file (generated by our own projection/team models) and an
# optional file you upload here (CSV, JSON, or delimited text), which
# overrides matching entries and leaves everything else untouched. Nothing
# on this page ever fetches a sportsbook, and nothing here places a bet --
# every number is a side-by-side comparison of our fair line against odds
# you supplied.
#
# NFL and NBA share this page's UI and the same underlying contract
# (default file + upload, real per-game rates, disclosed "basis" on every
# generated line) but are evaluated by separate, sport-specific modules --
# see architecture.md / betting_engine.md for why the two engines aren't
# merged into one codebase. NFL: fantasy_engine/betting/*. NBA: modules/nba_*.py.
#
# Performance notes (see performance_notes.md): every real-data loader used
# here is TTL-cached at the module level (modules/nba_schedule.py,
# modules/nba_props_loader.py, modules/nba_odds_loader.py,
# betting/odds_loader.py, betting/team_model.py), so the page-level
# @st.cache_data below is a second, Streamlit-specific layer on top of an
# already-cached call, not the only caching in play. Each sport's props/
# money-lines/parlays evaluation is computed once per render and reused
# across tabs (previously this page called evaluate_props/
# price_aware_evaluations a second time inside the Parlays tab).

from typing import Any

import pandas as pd
import streamlit as st

from app.page_runtime import apply_global_theme, empty_state, page_header, section_header

from betting.odds_loader import OddsLoadError, unified_odds
from betting.parlay_engine import evaluate_parlay, make_leg
from betting.prop_model import evaluate_props
from betting.moneyline_model import evaluate_games
from betting.team_model import team_scoring_averages as nfl_team_scoring_averages
from fantasy.projections import load_forward_projections, upcoming_season

from modules.async_upload import parse_uploads_concurrently
from modules.nba_moneyline_model import evaluate_games as nba_evaluate_games
from modules.nba_odds_loader import GameOddsLoadError, index_by_matchup, unified_game_odds
from modules.nba_parlay_engine import evaluate_parlay as nba_evaluate_parlay, make_leg as nba_make_leg
from modules.nba_prop_model import index_props_by_player_and_category, price_aware_evaluations
from modules.nba_props_loader import unified_props as nba_unified_props
from modules.nba_schedule import fetch_todays_games
from modules.nba_team_model import real_margin_and_total_volatility, team_scoring_averages as nba_team_scoring_averages
from modules.nba_advanced import latest_season as nba_latest_season
from modules.recommendations import recommend_props as nba_recommend_props
from modules.nba_trend_signals import player_usage_trend, team_pace_trend
from modules.unified_parlay_engine import evaluate_cross_sport_parlay, make_unified_leg

apply_global_theme()

page_header(
    "Betting Engine",
    "Offline fair-line analysis for props, money lines, and parlays -- odds come only from our own "
    "default file or a file you upload here, never a sportsbook. Nothing on this page places a bet.",
    eyebrow="Betting · fair lines vs. your odds",
)

sport = st.radio("Sport", ["NFL", "NBA"], horizontal=True, key="betting_engine_sport")

props_tab, moneylines_tab, parlays_tab, comparison_tab, cross_sport_tab = st.tabs(
    ["Player Props", "Money Lines", "Parlays", "Player Comparison", "Cross-Sport Parlay"]
)

# =========================================================================
# Cached page-level data loaders
# =========================================================================


@st.cache_data(show_spinner=False, ttl=60 * 60)
def _nfl_players(season: int) -> list[dict[str, Any]]:
    return load_forward_projections(season=season)


@st.cache_data(show_spinner=False, ttl=60 * 60)
def _nfl_team_averages(season: int) -> dict[str, dict[str, float]]:
    return nfl_team_scoring_averages(season)


@st.cache_data(show_spinner=False, ttl=60 * 60)
def _nba_team_averages(season: str) -> dict[str, dict[str, float]]:
    return nba_team_scoring_averages(season)


@st.cache_data(show_spinner=False, ttl=60 * 60)
def _nba_volatility(season: str) -> dict[str, float]:
    return real_margin_and_total_volatility(season)


@st.cache_data(show_spinner=False, ttl=15 * 60)
def _nba_todays_games() -> list[dict[str, Any]]:
    return fetch_todays_games()


@st.cache_data(show_spinner=False, ttl=15 * 60)
def _nba_recommendations(season: str, max_players: int) -> list[dict[str, Any]]:
    return nba_recommend_props(min_edge=0.0, min_confidence=0.0, min_reliability=0.0, season=season, max_players=max_players)


def _load_nfl_evaluations(uploader_key: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], dict[str, dict[str, float]]]:
    """Load NFL odds + real players, and return (prop_evaluations, game_evaluations, team_averages)."""
    source_season = upcoming_season() - 1
    with st.expander("Odds source", expanded=True):
        st.caption(
            "Default odds are generated by our own model from real per-game rates and real team scoring -- "
            "not fetched from any sportsbook. Upload a file below to override or add to them; only the "
            "entries your file names are replaced, everything else stays on our default."
        )
        uploaded_file = st.file_uploader(
            "Upload NFL odds (CSV, JSON, or text) to override our defaults",
            type=["csv", "json", "txt"],
            key=uploader_key,
        )
        try:
            odds = unified_odds(uploaded=uploaded_file if uploaded_file is not None else None)
        except OddsLoadError as error:
            st.error(f"Could not parse the uploaded odds file: {error}")
            odds = unified_odds()
        st.success(f"{len(odds['player_props'])} player props · {len(odds['games'])} games loaded.")

    players = _nfl_players(source_season)
    players_by_id = {str(player.get("player_id")): player for player in players}
    team_averages = _nfl_team_averages(source_season)
    prop_evaluations = evaluate_props(players_by_id, odds)
    game_evaluations = evaluate_games(odds, averages=team_averages)
    return prop_evaluations, game_evaluations, team_averages


def _load_nba_evaluations(
    props_uploader_key: str, odds_uploader_key: str, *, max_players: int = 20
) -> tuple[list[dict[str, Any]], list[dict[str, Any]], list[dict[str, Any]], dict[str, Any]]:
    """Load NBA odds + real schedule, and return (priced_props, raw_props, game_evaluations, extra_context)."""
    nba_season = nba_latest_season()
    with st.expander("Odds source", expanded=True):
        st.caption(
            "Default NBA prop lines are generated by our own model from real per-game rates (see "
            "modules/nba_props_generator.py) -- not fetched from any sportsbook. Game odds have no fixed "
            "default (NBA's daily schedule changes every day); upload a file below, or rely on our fair "
            "lines alone, computed live from real team scoring."
        )
        uploaded_props_file = st.file_uploader(
            "Upload NBA player props (CSV, JSON, or text) to override our defaults",
            type=["csv", "json", "txt"],
            key=props_uploader_key,
        )
        uploaded_game_odds_file = st.file_uploader(
            "Upload NBA game odds (CSV, JSON, or text) -- moneyline / spread / total",
            type=["csv", "json", "txt"],
            key=odds_uploader_key,
        )

        # Two independent uploads -- parse concurrently rather than one
        # after the other (see modules/async_upload.py). At today's file
        # sizes the wall-clock win is modest; the spinner is what actually
        # keeps the page from looking frozen while either parse runs.
        with st.spinner("Loading odds sources..."):
            try:
                results = parse_uploads_concurrently(
                    {
                        "props": lambda: nba_unified_props(uploaded=uploaded_props_file if uploaded_props_file is not None else None),
                        "game_odds": lambda: unified_game_odds(uploaded=uploaded_game_odds_file if uploaded_game_odds_file is not None else None),
                    }
                )
                nba_props = results["props"]
                nba_game_odds = results["game_odds"]
            except GameOddsLoadError as error:
                st.error(f"Could not parse the uploaded game-odds file: {error}")
                nba_props = nba_unified_props(uploaded=uploaded_props_file if uploaded_props_file is not None else None)
                nba_game_odds = unified_game_odds()
        st.success(f"{len(nba_props)} player props · {len(nba_game_odds['games'])} game odds loaded.")

    todays_games = _nba_todays_games()
    if not todays_games:
        st.info("No real NBA games are scheduled today -- Money Lines and live-matchup Props below will be empty until game day.")

    recommendations: list[dict[str, Any]] = []
    if todays_games:
        with st.spinner("Scanning today's real matchups..."):
            recommendations = _nba_recommendations(nba_season, max_players)
    props_by_key = index_props_by_player_and_category(nba_props)
    priced = price_aware_evaluations(recommendations, props_by_key) if recommendations else []

    game_evaluations: list[dict[str, Any]] = []
    if todays_games:
        nba_averages = _nba_team_averages(nba_season)
        nba_volatility = _nba_volatility(nba_season)
        odds_by_matchup = index_by_matchup(nba_game_odds)
        game_evaluations = nba_evaluate_games(todays_games, averages=nba_averages, odds_by_matchup=odds_by_matchup, volatility=nba_volatility)

    extra = {"season": nba_season, "todays_games": todays_games, "raw_props": nba_props}
    return priced, nba_props, game_evaluations, extra


# =========================================================================
# Load the current sport's data once, reused across every tab below
# =========================================================================

if sport == "NFL":
    nfl_prop_evaluations, nfl_game_evaluations, nfl_team_averages = _load_nfl_evaluations("betting_odds_upload_nfl")
else:
    nba_priced_props, nba_raw_props, nba_game_evaluations, nba_extra = _load_nba_evaluations(
        "betting_props_upload_nba", "betting_game_odds_upload_nba"
    )
    nba_season = nba_extra["season"]
    nba_todays_games = nba_extra["todays_games"]

# -----------------------------------------------------------------------
# Player Props
# -----------------------------------------------------------------------
with props_tab:
    section_header(
        "Player Props",
        "Our model's probability of over/under against the loaded odds, ranked by edge.",
    )
    if sport == "NFL":
        prop_evaluations = nfl_prop_evaluations
        if not prop_evaluations:
            empty_state(
                "No props to evaluate",
                "The loaded odds don't include any player props this pool can price, or none of the "
                "props' players matched a real player. Try uploading a props file.",
                icon="🏈",
            )
        else:
            col1, col2, col3 = st.columns(3)
            markets = sorted({row["market"] for row in prop_evaluations})
            market_filter = col1.multiselect("Market", markets, key="props_market_filter")
            risk_filter = col2.multiselect("Risk tier", ["low", "medium", "high"], key="props_risk_filter")
            min_edge = col3.slider("Minimum edge", 0.0, 0.5, 0.0, 0.01, key="props_min_edge")

            filtered = [
                row
                for row in prop_evaluations
                if (not market_filter or row["market"] in market_filter)
                and (not risk_filter or row["risk_tier"] in risk_filter)
                and row["recommended_edge"] >= min_edge
            ]
            st.caption(f"{len(filtered)} of {len(prop_evaluations)} props shown. Click a column header to sort.")
            table = pd.DataFrame(
                [
                    {
                        "Player": row["name"],
                        "Team": row["team"],
                        "Market": row["market"],
                        "Line": row["line"],
                        "Model mean": row["distribution"]["mean"],
                        "Side": row["recommended_side"],
                        "Model prob.": row[f"model_probability_{row['recommended_side']}"],
                        "Fair prob. (odds)": row[f"market_fair_probability_{row['recommended_side']}"],
                        "Edge": row["recommended_edge"],
                        "EV / $100": row["recommended_ev"],
                        "Confidence": row["confidence"],
                        "Risk": row["risk_tier"],
                        "Odds source": row["odds_source"],
                    }
                    for row in filtered
                ]
            )
            st.dataframe(
                table,
                width="stretch",
                hide_index=True,
                column_config={
                    "Model prob.": st.column_config.NumberColumn(format="%.1%"),
                    "Fair prob. (odds)": st.column_config.NumberColumn(format="%.1%"),
                    "Edge": st.column_config.NumberColumn(format="%.1%"),
                    "EV / $100": st.column_config.NumberColumn(format="%+.2f"),
                    "Confidence": st.column_config.NumberColumn(format="%.0%"),
                },
            )
    else:
        priced = nba_priced_props
        if priced:
            col1, col2 = st.columns(2)
            categories = sorted({row["category"] for row in priced})
            category_filter = col1.multiselect("Category", categories, key="nba_props_category_filter")
            min_ev = col2.slider("Minimum |EV| / $100", 0.0, 20.0, 0.0, 0.5, key="nba_props_min_ev")
            filtered = [
                row
                for row in priced
                if (not category_filter or row["category"] in category_filter) and abs(row["recommended_priced_ev"]) >= min_ev
            ]

            show_trends = st.checkbox(
                "Show pace / usage trend overlay (real, cached -- adds a live-derived column per shown row)",
                key="nba_props_show_trends",
            )
            st.caption(f"{len(filtered)} of {len(priced)} priced props shown. Click a column header to sort.")

            rows = []
            for row in filtered:
                entry = {
                    "Player": row["player"],
                    "Team": row["team"],
                    "Category": row["category"],
                    "Line": row["sportsbook_line"],
                    "Model proj.": row["minutes_adjusted_projection"],
                    "Side": row["recommended_priced_side"],
                    "Model prob.": row[f"model_probability_{row['recommended_priced_side']}"],
                    "Fair prob. (odds)": row[f"market_fair_probability_{row['recommended_priced_side']}"],
                    "EV / $100": row["recommended_priced_ev"],
                    "Risk": row.get("risk_tier", ""),
                    "Reliability": row.get("confidence_score", ""),
                }
                if show_trends:
                    try:
                        pace = team_pace_trend(row["team"], nba_season)
                        entry["Pace trend"] = pace["trend"]
                        entry["Pace Δ"] = pace["pace_delta"]
                    except Exception:
                        entry["Pace trend"], entry["Pace Δ"] = "n/a", None
                    try:
                        usage = player_usage_trend(row["player"], nba_season)
                        entry["Usage trend"] = usage["trend"]
                        entry["Usage Δ (pts)"] = usage["usage_delta"]
                    except Exception:
                        entry["Usage trend"], entry["Usage Δ (pts)"] = "n/a", None
                rows.append(entry)

            table = pd.DataFrame(rows)
            st.dataframe(
                table,
                width="stretch",
                hide_index=True,
                column_config={
                    "Model prob.": st.column_config.NumberColumn(format="%.1%"),
                    "Fair prob. (odds)": st.column_config.NumberColumn(format="%.1%"),
                    "EV / $100": st.column_config.NumberColumn(format="%+.2f"),
                },
            )
        else:
            empty_state(
                "No priced props to evaluate",
                "This needs both a real game today (for matchup-adjusted projections) and a loaded prop "
                "line for the same player/category. On a non-game day, browse the raw default lines "
                "below instead.",
                icon="🏀",
            )
            if nba_raw_props:
                st.caption(f"{len(nba_raw_props)} default/uploaded prop lines available (season per-game rates, no live matchup adjustment):")
                st.dataframe(
                    pd.DataFrame(
                        [
                            {"Player": row["player_name"], "Team": row["team"], "Category": row["category"], "Line": row["line"], "Basis": row.get("basis", "")}
                            for row in sorted(nba_raw_props, key=lambda r: (r["player_name"], r["category"]))[:200]
                        ]
                    ),
                    width="stretch",
                    hide_index=True,
                )

        with st.expander("Look up a single team/player trend"):
            st.caption(
                "Real season vs. real last-10-games splits from the NBA's own stats API. See "
                "modules/nba_trend_signals.py."
            )
            trend_col1, trend_col2 = st.columns(2)
            team_for_trend = trend_col1.text_input("Team pace trend", "DEN", key="nba_pace_trend_team")
            player_for_trend = trend_col2.text_input("Player usage trend", "Nikola Jokic", key="nba_usage_trend_player")
            if st.button("Check trends", key="nba_trend_check_button"):
                try:
                    st.json(team_pace_trend(team_for_trend, nba_season))
                except Exception as error:
                    st.warning(f"Could not compute pace trend for {team_for_trend!r}: {error}")
                try:
                    st.json(player_usage_trend(player_for_trend, nba_season))
                except Exception as error:
                    st.warning(f"Could not compute usage trend for {player_for_trend!r}: {error}")

# -----------------------------------------------------------------------
# Money Lines
# -----------------------------------------------------------------------
with moneylines_tab:
    section_header(
        "Money Lines",
        "Fair spread, total, and moneyline from real team scoring this season, compared to the loaded odds.",
    )
    if sport == "NFL":
        game_evaluations = nfl_game_evaluations
        if not game_evaluations:
            empty_state(
                "No games to evaluate",
                "The loaded odds don't include any game lines. Upload a game-odds file (home_team, "
                "away_team, moneyline_home, moneyline_away, total_line, ...) to populate this tab.",
                icon="🏟️",
            )
        else:
            rows = []
            for game in game_evaluations:
                model = game["model"]
                moneyline = game.get("moneyline")
                total = game.get("total")
                rows.append(
                    {
                        "Home": game["home_team"],
                        "Away": game["away_team"],
                        "Model spread (home)": model["spread"],
                        "Model total": model["total"],
                        "Home win prob.": model["home_win_probability"],
                        "Fair home ML": model["fair_home_moneyline"],
                        "Market home ML": moneyline["home_price"] if moneyline else None,
                        "ML edge": moneyline["recommended_edge"] if moneyline else None,
                        "ML side": moneyline["recommended_side"] if moneyline else None,
                        "Total line": total["line"] if total else None,
                        "Total edge": total["recommended_edge"] if total else None,
                        "Total side": total["recommended_side"] if total else None,
                    }
                )
            table = pd.DataFrame(rows).sort_values(
                by=[c for c in ("ML edge", "Total edge") if True], ascending=False, na_position="last"
            )
            st.caption("Click a column header to sort.")
            st.dataframe(
                table,
                width="stretch",
                hide_index=True,
                column_config={
                    "Home win prob.": st.column_config.NumberColumn(format="%.1%"),
                    "ML edge": st.column_config.NumberColumn(format="%.1%"),
                    "Total edge": st.column_config.NumberColumn(format="%.1%"),
                },
            )
    else:
        if not nba_todays_games:
            empty_state(
                "No NBA games today",
                "Money lines are evaluated for today's real schedule only -- there is nothing to price "
                "when no games are on. Check back on a game day.",
                icon="🏀",
            )
        else:
            game_evaluations = nba_game_evaluations
            rows = []
            for game in game_evaluations:
                model = game["model"]
                moneyline = game.get("moneyline")
                total = game.get("total")
                rows.append(
                    {
                        "Home": game["home_team"],
                        "Away": game["away_team"],
                        "Model spread (home)": model["spread"],
                        "Model total": model["total"],
                        "Home win prob.": model["home_win_probability"],
                        "Fair home ML": model["fair_home_moneyline"],
                        "Market home ML": moneyline["home_price"] if moneyline else None,
                        "ML edge": moneyline["recommended_edge"] if moneyline else None,
                        "Total line": total["line"] if total else None,
                        "Total edge": total["recommended_edge"] if total else None,
                    }
                )
            table = pd.DataFrame(rows).sort_values(by=[c for c in ("ML edge", "Total edge") if True], ascending=False, na_position="last")
            nba_volatility = _nba_volatility(nba_season)
            st.caption(f"Margin volatility: {nba_volatility['margin_stdev']} pts, total volatility: {nba_volatility['total_stdev']} pts ({nba_volatility['basis']}). Click a column header to sort.")
            st.dataframe(
                table,
                width="stretch",
                hide_index=True,
                column_config={
                    "Home win prob.": st.column_config.NumberColumn(format="%.1%"),
                    "ML edge": st.column_config.NumberColumn(format="%.1%"),
                    "Total edge": st.column_config.NumberColumn(format="%.1%"),
                },
            )


def _parlay_builder(*, prop_evaluations: list[dict[str, Any]], sport_key: str, empty_icon: str) -> None:
    """Shared parlay-builder UX for one sport: quick-add top edges, leg summary, evaluation. NFL and NBA render identically here."""
    if sport_key == "NFL":
        options = {f"{row['name']} {row['market']} {row['recommended_side']} {row['line']}": row for row in prop_evaluations}
        side_key, edge_key, price_prefix = "recommended_side", "recommended_edge", ""
    else:
        options = {f"{row['player']} {row['category']} {row['recommended_priced_side']} {row['sportsbook_line']}": row for row in prop_evaluations}
        side_key, edge_key, price_prefix = "recommended_priced_side", "recommended_priced_ev", ""

    if len(options) < 2:
        empty_state("Not enough props loaded to build a parlay", "A parlay needs at least two legs -- load more props first.", icon=empty_icon)
        return

    ranked_labels = sorted(options, key=lambda label: -abs(options[label][edge_key]))
    picker_key = f"{sport_key}_parlay_leg_picker"
    # Streamlit forbids passing both `default=` and pre-setting session_state
    # for the same widget key -- seed/reseed session_state here instead and
    # let the widget read purely from it, so the Quick-add button's
    # session_state write below never conflicts with a `default=`. Reseed
    # (not just seed-once) whenever the stored selection contains a label
    # that's no longer in the current options (e.g. after a new upload
    # changes the available props) -- an empty selection is always valid,
    # but a stale one would make the widget itself raise.
    stored = st.session_state.get(picker_key)
    if stored is None or any(label not in options for label in stored):
        st.session_state[picker_key] = ranked_labels[: min(3, len(options))]

    quick_add_col, _ = st.columns([1, 3])
    quick_add_n = quick_add_col.number_input("Quick-add top N by edge", min_value=2, max_value=min(8, len(options)), value=min(3, len(options)), key=f"{sport_key}_quick_add_n")
    if quick_add_col.button("Quick-add", key=f"{sport_key}_quick_add_button"):
        st.session_state[picker_key] = ranked_labels[:quick_add_n]

    chosen_labels = st.multiselect(
        "Legs",
        list(options),
        key=picker_key,
        help="Each leg uses the model's recommended side and its own price from the loaded odds.",
    )
    if len(chosen_labels) < 2:
        st.info("Pick at least 2 legs to evaluate a parlay.")
        return

    summary_rows = []
    legs = []
    for label in chosen_labels:
        row = options[label]
        side = row[side_key]
        if sport_key == "NFL":
            leg = make_leg(
                description=label, model_probability=row[f"model_probability_{side}"], price=row[f"{side}_price"],
                player_id=row["player_id"], team=row["team"], market=row["market"], side=side, confidence=row["confidence"],
            )
            summary_rows.append({"Leg": label, "Model prob.": row[f"model_probability_{side}"], "Edge": row["recommended_edge"], "Risk": row.get("risk_tier", "")})
        else:
            leg = nba_make_leg(
                description=label, model_probability=row[f"model_probability_{side}"], price=row[f"{side}_price"],
                player_id=row["player"], team=row["team"], market=row["category"], side=side, confidence=row.get("confidence_score", 70.0) / 100.0,
            )
            summary_rows.append({"Leg": label, "Model prob.": row[f"model_probability_{side}"], "EV / $100": row["recommended_priced_ev"], "Risk": row.get("risk_tier", "")})
        legs.append(leg)

    st.dataframe(pd.DataFrame(summary_rows), width="stretch", hide_index=True, column_config={"Model prob.": st.column_config.NumberColumn(format="%.1%")})

    result = (evaluate_parlay if sport_key == "NFL" else nba_evaluate_parlay)(legs)
    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Adjusted hit probability", f"{result['adjusted_hit_probability']:.1%}")
    m2.metric("Payout / $100", f"${result['payout_per_100_stake']:,.2f}")
    m3.metric("Adjusted EV / $100", f"${result['adjusted_ev']:+,.2f}")
    m4.metric("Confidence", f"{result['confidence']:.0%}", help=f"Risk tier: {result['risk_tier']}")

    if result["correlations_detected"]:
        st.warning(f"Correlated legs detected -- hit probability adjusted from the naive {result['naive_hit_probability']:.1%} to {result['adjusted_hit_probability']:.1%}.")
        for finding in result["correlations_detected"]:
            leg_a, leg_b = finding["legs"]
            st.caption(f"- {legs[leg_a]['description']} + {legs[leg_b]['description']}: {finding['note']}")
    else:
        st.caption("No known correlation pattern detected between these legs.")


# -----------------------------------------------------------------------
# Parlays
# -----------------------------------------------------------------------
with parlays_tab:
    section_header("Parlays", "Build a parlay from the props above -- correlation-adjusted hit probability, EV, and risk.")
    if sport == "NFL":
        _parlay_builder(prop_evaluations=nfl_prop_evaluations, sport_key="NFL", empty_icon="🧩")
    else:
        _parlay_builder(prop_evaluations=nba_priced_props, sport_key="NBA", empty_icon="🧩")

# -----------------------------------------------------------------------
# Player Comparison
# -----------------------------------------------------------------------
with comparison_tab:
    section_header("Player Comparison", "Side-by-side edge, EV, and confidence for two priced props -- same sport as the toggle above.")
    if sport == "NFL":
        rows_for_compare = nfl_prop_evaluations
        label_fn = lambda row: f"{row['name']} {row['market']} {row['line']}"
    else:
        rows_for_compare = nba_priced_props
        label_fn = lambda row: f"{row['player']} {row['category']} {row['sportsbook_line']}"

    if len(rows_for_compare) < 2:
        empty_state("Not enough priced props to compare", "Load more props in the Player Props tab first.", icon="🔬")
    else:
        options = {label_fn(row): row for row in rows_for_compare}
        col1, col2 = st.columns(2)
        left_label = col1.selectbox("Player / prop A", list(options), index=0, key=f"{sport}_compare_left")
        right_label = col2.selectbox("Player / prop B", list(options), index=min(1, len(options) - 1), key=f"{sport}_compare_right")
        left, right = options[left_label], options[right_label]

        if sport == "NFL":
            metrics = [
                ("Market", "market"), ("Line", "line"), ("Recommended side", "recommended_side"),
                ("Edge", "recommended_edge"), ("EV / $100", "recommended_ev"), ("Confidence", "confidence"), ("Risk", "risk_tier"),
            ]
        else:
            metrics = [
                ("Category", "category"), ("Line", "sportsbook_line"), ("Recommended side", "recommended_priced_side"),
                ("EV / $100", "recommended_priced_ev"), ("Reliability", "confidence_score"), ("Risk", "risk_tier"),
            ]
        # Each row mixes numbers and strings across different metrics (e.g.
        # "Line" is a float, "Recommended side" is a string) -- stringify
        # for display so the column has one consistent dtype instead of
        # letting pandas/pyarrow silently coerce a mixed-type object column.
        comparison_table = pd.DataFrame(
            [{"Metric": label, left_label: str(left.get(key, "")), right_label: str(right.get(key, ""))} for label, key in metrics]
        )
        st.dataframe(comparison_table, width="stretch", hide_index=True)

# -----------------------------------------------------------------------
# Cross-Sport Parlay
# -----------------------------------------------------------------------
with cross_sport_tab:
    section_header(
        "Cross-Sport Parlay",
        "Combine NFL and NBA legs in one parlay. Each sport's own correlation patterns are still detected "
        "within that sport's legs; an NFL leg and an NBA leg are never treated as correlated with each other.",
    )
    st.caption(
        "Loads whichever sport isn't already loaded above (cached, so switching the sport toggle first costs nothing extra)."
    )
    if st.button("Load NFL + NBA legs for a cross-sport parlay", key="cross_sport_load_button"):
        with st.spinner("Loading both sports..."):
            if sport == "NFL":
                cs_nfl_props = nfl_prop_evaluations
                cs_nba_priced, _, _, _ = _load_nba_evaluations("cross_sport_nba_props_upload", "cross_sport_nba_odds_upload")
            else:
                cs_nba_priced = nba_priced_props
                cs_nfl_props, _, _ = _load_nfl_evaluations("cross_sport_nfl_odds_upload")
        st.session_state["cross_sport_nfl_props"] = cs_nfl_props
        st.session_state["cross_sport_nba_props"] = cs_nba_priced

    cs_nfl_props = st.session_state.get("cross_sport_nfl_props")
    cs_nba_props = st.session_state.get("cross_sport_nba_props")

    if not cs_nfl_props or not cs_nba_props:
        empty_state(
            "Load both sports to build a cross-sport parlay",
            "Click the button above -- it reuses whatever's already loaded for the current sport toggle "
            "and fetches the other sport once.",
            icon="🌐",
        )
    else:
        nfl_options = {f"NFL: {row['name']} {row['market']} {row['recommended_side']} {row['line']}": row for row in cs_nfl_props}
        nba_options = {f"NBA: {row['player']} {row['category']} {row['recommended_priced_side']} {row['sportsbook_line']}": row for row in cs_nba_props}
        combined_options = {**nfl_options, **nba_options}

        chosen_labels = st.multiselect(
            "Legs (mix NFL and NBA freely)",
            list(combined_options),
            default=(list(nfl_options)[:1] + list(nba_options)[:1]),
            key="cross_sport_leg_picker",
        )
        if len(chosen_labels) < 2:
            st.info("Pick at least 2 legs (from either or both sports) to evaluate a cross-sport parlay.")
        else:
            legs = []
            for label in chosen_labels:
                if label in nfl_options:
                    row = nfl_options[label]
                    side = row["recommended_side"]
                    legs.append(make_unified_leg(
                        "NFL", description=label, model_probability=row[f"model_probability_{side}"], price=row[f"{side}_price"],
                        player_id=row["player_id"], team=row["team"], market=row["market"], side=side, confidence=row["confidence"],
                    ))
                else:
                    row = nba_options[label]
                    side = row["recommended_priced_side"]
                    legs.append(make_unified_leg(
                        "NBA", description=label, model_probability=row[f"model_probability_{side}"], price=row[f"{side}_price"],
                        player_id=row["player"], team=row["team"], market=row["category"], side=side, confidence=row.get("confidence_score", 70.0) / 100.0,
                    ))

            result = evaluate_cross_sport_parlay(legs)
            st.caption(f"Sports in this parlay: {', '.join(result['sports'])}")
            m1, m2, m3, m4 = st.columns(4)
            m1.metric("Adjusted hit probability", f"{result['adjusted_hit_probability']:.1%}")
            m2.metric("Payout / $100", f"${result['payout_per_100_stake']:,.2f}")
            m3.metric("Adjusted EV / $100", f"${result['adjusted_ev']:+,.2f}")
            m4.metric("Confidence", f"{result['confidence']:.0%}", help=f"Risk tier: {result['risk_tier']}")

            if result["correlations_detected"]:
                st.warning(f"Correlated legs detected within one sport -- hit probability adjusted from the naive {result['naive_hit_probability']:.1%} to {result['adjusted_hit_probability']:.1%}.")
                for finding in result["correlations_detected"]:
                    leg_a, leg_b = finding["legs"]
                    st.caption(f"- {legs[leg_a]['description']} + {legs[leg_b]['description']}: {finding['note']}")
            else:
                st.caption("No known correlation pattern detected between these legs (cross-sport pairs are never correlated).")
