import sys
from pathlib import Path

_PROJECT_ROOT = str(Path(__file__).resolve().parents[2])
while _PROJECT_ROOT in sys.path:
    sys.path.remove(_PROJECT_ROOT)
sys.path.insert(0, _PROJECT_ROOT)
_loaded_app = sys.modules.get("app")
if _loaded_app is not None and not hasattr(_loaded_app, "__path__"):
    del sys.modules["app"]

_FANTASY_ENGINE_ROOT = Path(__file__).resolve().parents[3] / "fantasy_engine"
if _FANTASY_ENGINE_ROOT.is_dir() and str(_FANTASY_ENGINE_ROOT) not in sys.path:
    sys.path.insert(0, str(_FANTASY_ENGINE_ROOT))

# Betting Engine: offline, deterministic fair-line analysis across three
# markets -- Player Props, Money Lines, Parlays.
#
# Odds come from exactly two places, both offline: our own default
# odds.json (generated by our own projection/team models -- see
# betting/odds_generator.py) and an optional file you upload here (CSV,
# JSON, or delimited text), which overrides matching entries and leaves
# everything else untouched. Nothing on this page ever fetches a
# sportsbook, and nothing here places a bet -- every number is a
# side-by-side comparison of our fair line against odds you supplied.
#
# All calculations are delegated to the `betting` engine package
# (`fantasy_engine/betting`); this page only handles presentation.

from typing import Any

import pandas as pd
import streamlit as st

from app.page_runtime import apply_global_theme, empty_state, page_header, section_header

from betting.odds_loader import OddsLoadError, unified_odds
from betting.parlay_engine import detect_correlations, evaluate_parlay, make_leg
from betting.prop_model import evaluate_props
from betting.moneyline_model import evaluate_games
from betting.team_model import team_scoring_averages
from fantasy.projections import load_forward_projections, upcoming_season

apply_global_theme()

page_header(
    "Betting Engine",
    "Offline fair-line analysis for props, money lines, and parlays -- odds come only from our own "
    "default file or a file you upload here, never a sportsbook. Nothing on this page places a bet.",
    eyebrow="Betting · fair lines vs. your odds",
)


@st.cache_data(show_spinner=False, ttl=60 * 60)
def _load_players(season: int) -> list[dict[str, Any]]:
    return load_forward_projections(season=season)


@st.cache_data(show_spinner=False, ttl=60 * 60)
def _load_team_averages(season: int) -> dict[str, dict[str, float]]:
    return team_scoring_averages(season)


source_season = upcoming_season() - 1

with st.expander("Odds source", expanded=True):
    st.caption(
        "Default odds are generated by our own model from real per-game rates and real team scoring -- "
        "not fetched from any sportsbook. Upload a file below to override or add to them; only the "
        "entries your file names are replaced, everything else stays on our default."
    )
    uploaded_file = st.file_uploader(
        "Upload odds (CSV, JSON, or text) to override our defaults",
        type=["csv", "json", "txt"],
        key="betting_odds_upload",
    )
    uploaded_odds_source: Any = None
    if uploaded_file is not None:
        uploaded_odds_source = uploaded_file
    try:
        odds = unified_odds(uploaded=uploaded_odds_source)
    except OddsLoadError as error:
        st.error(f"Could not parse the uploaded odds file: {error}")
        odds = unified_odds()
    st.success(f"{len(odds['player_props'])} player props · {len(odds['games'])} games loaded.")

players = _load_players(source_season)
players_by_id = {str(player.get("player_id")): player for player in players}
team_averages = _load_team_averages(source_season)

props_tab, moneylines_tab, parlays_tab = st.tabs(["Player Props", "Money Lines", "Parlays"])

# -----------------------------------------------------------------------
# Player Props
# -----------------------------------------------------------------------
with props_tab:
    section_header(
        "Player Props",
        "Our model's probability of over/under against the loaded odds, ranked by edge.",
    )
    prop_evaluations = evaluate_props(players_by_id, odds)
    if not prop_evaluations:
        empty_state(
            "No props to evaluate",
            "The loaded odds don't include any player props this pool can price, or none of the "
            "props' players matched a real player. Try uploading a props file.",
            icon="🏈",
        )
    else:
        col1, col2, col3 = st.columns(3)
        markets = sorted({row["market"] for row in prop_evaluations})
        market_filter = col1.multiselect("Market", markets, key="props_market_filter")
        risk_filter = col2.multiselect("Risk tier", ["low", "medium", "high"], key="props_risk_filter")
        min_edge = col3.slider("Minimum edge", 0.0, 0.5, 0.0, 0.01, key="props_min_edge")

        filtered = [
            row
            for row in prop_evaluations
            if (not market_filter or row["market"] in market_filter)
            and (not risk_filter or row["risk_tier"] in risk_filter)
            and row["recommended_edge"] >= min_edge
        ]
        st.caption(f"{len(filtered)} of {len(prop_evaluations)} props shown.")
        table = pd.DataFrame(
            [
                {
                    "Player": row["name"],
                    "Team": row["team"],
                    "Market": row["market"],
                    "Line": row["line"],
                    "Model mean": row["distribution"]["mean"],
                    "Side": row["recommended_side"],
                    "Model prob.": row[f"model_probability_{row['recommended_side']}"],
                    "Fair prob. (odds)": row[f"market_fair_probability_{row['recommended_side']}"],
                    "Edge": row["recommended_edge"],
                    "EV / $100": row["recommended_ev"],
                    "Confidence": row["confidence"],
                    "Risk": row["risk_tier"],
                    "Odds source": row["odds_source"],
                }
                for row in filtered
            ]
        )
        st.dataframe(
            table,
            width="stretch",
            hide_index=True,
            column_config={
                "Model prob.": st.column_config.NumberColumn(format="%.1%"),
                "Fair prob. (odds)": st.column_config.NumberColumn(format="%.1%"),
                "Edge": st.column_config.NumberColumn(format="%.1%"),
                "EV / $100": st.column_config.NumberColumn(format="%+.2f"),
                "Confidence": st.column_config.NumberColumn(format="%.0%"),
            },
        )

# -----------------------------------------------------------------------
# Money Lines
# -----------------------------------------------------------------------
with moneylines_tab:
    section_header(
        "Money Lines",
        "Fair spread, total, and moneyline from real team scoring this season, compared to the loaded odds.",
    )
    game_evaluations = evaluate_games(odds, averages=team_averages)
    if not game_evaluations:
        empty_state(
            "No games to evaluate",
            "The loaded odds don't include any game lines. Upload a game-odds file (home_team, "
            "away_team, moneyline_home, moneyline_away, total_line, ...) to populate this tab.",
            icon="🏟️",
        )
    else:
        rows = []
        for game in game_evaluations:
            model = game["model"]
            moneyline = game.get("moneyline")
            total = game.get("total")
            rows.append(
                {
                    "Home": game["home_team"],
                    "Away": game["away_team"],
                    "Model spread (home)": model["spread"],
                    "Model total": model["total"],
                    "Home win prob.": model["home_win_probability"],
                    "Fair home ML": model["fair_home_moneyline"],
                    "Market home ML": moneyline["home_price"] if moneyline else None,
                    "ML edge": moneyline["recommended_edge"] if moneyline else None,
                    "ML side": moneyline["recommended_side"] if moneyline else None,
                    "Total line": total["line"] if total else None,
                    "Total edge": total["recommended_edge"] if total else None,
                    "Total side": total["recommended_side"] if total else None,
                }
            )
        table = pd.DataFrame(rows).sort_values(
            by=[c for c in ("ML edge", "Total edge") if True], ascending=False, na_position="last"
        )
        st.dataframe(
            table,
            width="stretch",
            hide_index=True,
            column_config={
                "Home win prob.": st.column_config.NumberColumn(format="%.1%"),
                "ML edge": st.column_config.NumberColumn(format="%.1%"),
                "Total edge": st.column_config.NumberColumn(format="%.1%"),
            },
        )

# -----------------------------------------------------------------------
# Parlays
# -----------------------------------------------------------------------
with parlays_tab:
    section_header(
        "Parlays",
        "Build a parlay from the props above -- correlation-adjusted hit probability, EV, and risk.",
    )
    prop_evaluations = evaluate_props(players_by_id, odds)
    if len(prop_evaluations) < 2:
        empty_state(
            "Not enough props loaded to build a parlay",
            "A parlay needs at least two legs -- load more props first.",
            icon="🧩",
        )
    else:
        options = {
            f"{row['name']} {row['market']} {row['recommended_side']} {row['line']}": row for row in prop_evaluations
        }
        chosen_labels = st.multiselect(
            "Legs",
            list(options),
            default=list(options)[: min(3, len(options))],
            key="parlay_leg_picker",
            help="Each leg uses the model's recommended side and its own price from the loaded odds.",
        )
        if len(chosen_labels) < 2:
            st.info("Pick at least 2 legs to evaluate a parlay.")
        else:
            legs = []
            for label in chosen_labels:
                row = options[label]
                side = row["recommended_side"]
                legs.append(
                    make_leg(
                        description=label,
                        model_probability=row[f"model_probability_{side}"],
                        price=row[f"{side}_price"],
                        player_id=row["player_id"],
                        team=row["team"],
                        market=row["market"],
                        side=side,
                        confidence=row["confidence"],
                    )
                )
            result = evaluate_parlay(legs)
            m1, m2, m3, m4 = st.columns(4)
            m1.metric("Adjusted hit probability", f"{result['adjusted_hit_probability']:.1%}")
            m2.metric("Payout / $100", f"${result['payout_per_100_stake']:,.2f}")
            m3.metric("Adjusted EV / $100", f"${result['adjusted_ev']:+,.2f}")
            m4.metric("Confidence", f"{result['confidence']:.0%}", help=f"Risk tier: {result['risk_tier']}")

            if result["correlations_detected"]:
                st.warning(
                    "Correlated legs detected -- hit probability adjusted from the naive "
                    f"{result['naive_hit_probability']:.1%} to {result['adjusted_hit_probability']:.1%}."
                )
                for finding in result["correlations_detected"]:
                    leg_a, leg_b = finding["legs"]
                    st.caption(f"- {legs[leg_a]['description']} + {legs[leg_b]['description']}: {finding['note']}")
            else:
                st.caption("No known correlation pattern detected between these legs.")
