"""Shared data loaders and tab renderers for the seven betting pages (30-36).

Extracted from the former single-page ``30_Betting_Engine.py`` (now split
per sport -- see ui_betting_tabs.md) so the six sport pages and the
Cross-Sport Tools page import one copy of each loader/render function
instead of six near-duplicates. Behavior is unchanged from the original
page: same caching, same odds-source disclosure text, same table columns.

Odds come from exactly two places, both offline, per sport: our own
default file (generated by our own projection/team models, where one
exists) and an optional file you upload (CSV, JSON, or delimited text),
which overrides matching entries and leaves everything else untouched.
Nothing here ever fetches a sportsbook, and nothing here places a bet.

  NFL: fantasy_engine/betting/*        NBA: modules/nba_*.py
  CFB: modules/cfb_*.py                CBB: modules/cbb_*.py
  MLB: modules/mlb_*.py                NHL: modules/nhl_*.py

CFB needs a College Football Data API key (set CFBD_API_KEY) for real
data -- ships empty-by-design otherwise; see cfb_pipeline.md. CBB uses
ESPN's public JSON API, no key required. MLB and NHL ship empty by
design -- no live/scraped source was integrated for either this cycle
(see mlb_pipeline.md / nhl_pipeline.md); both work fully from an uploaded
file.
"""
from __future__ import annotations

from typing import Any

import pandas as pd
import streamlit as st

from app.page_runtime import empty_state, section_header

from betting.odds_loader import OddsLoadError, unified_odds
from betting.parlay_engine import evaluate_parlay, make_leg
from betting.prop_model import evaluate_props
from betting.moneyline_model import evaluate_games
from betting.team_model import team_scoring_averages as nfl_team_scoring_averages
from fantasy.projections import load_forward_projections, upcoming_season

from modules.async_upload import parse_uploads_concurrently
from modules.nba_moneyline_model import evaluate_games as nba_evaluate_games
from modules.nba_odds_loader import GameOddsLoadError, index_by_matchup, unified_game_odds
from modules.nba_parlay_engine import evaluate_parlay as nba_evaluate_parlay, make_leg as nba_make_leg
from modules.nba_prop_model import index_props_by_player_and_category, price_aware_evaluations
from modules.nba_props_loader import unified_props as nba_unified_props
from modules.nba_schedule import fetch_todays_games
from modules.nba_team_model import real_margin_and_total_volatility, team_scoring_averages as nba_team_scoring_averages
from modules.nba_advanced import latest_season as nba_latest_season
from modules.recommendations import recommend_props as nba_recommend_props
from modules.nba_trend_signals import player_usage_trend, team_pace_trend

from modules.cfb_moneyline_model import evaluate_games as cfb_evaluate_games
from modules.cfb_odds_loader import GameOddsLoadError as CfbGameOddsLoadError, index_by_matchup as cfb_index_by_matchup, unified_game_odds as cfb_unified_game_odds
from modules.cfb_parlay_engine import evaluate_parlay as cfb_evaluate_parlay, make_leg as cfb_make_leg
from modules.cfb_prop_model import evaluate_props as cfb_evaluate_props
from modules.cfb_props_loader import unified_props as cfb_unified_props
from modules.cfb_team_model import fetch_week_games as cfb_fetch_week_games, real_margin_and_total_volatility as cfb_volatility, team_scoring_averages as cfb_team_scoring_averages

from modules.cbb_moneyline_model import evaluate_games as cbb_evaluate_games
from modules.cbb_odds_loader import GameOddsLoadError as CbbGameOddsLoadError, index_by_matchup as cbb_index_by_matchup, unified_game_odds as cbb_unified_game_odds
from modules.cbb_parlay_engine import evaluate_parlay as cbb_evaluate_parlay, make_leg as cbb_make_leg
from modules.cbb_prop_model import evaluate_props as cbb_evaluate_props
from modules.cbb_props_loader import unified_props as cbb_unified_props
from modules.cbb_schedule import fetch_todays_games as cbb_todays_games
from modules.cbb_team_model import build_team_scoring_averages as cbb_build_team_scoring_averages, real_margin_and_total_volatility as cbb_volatility

from modules.mlb_moneyline_model import evaluate_games as mlb_evaluate_games
from modules.mlb_odds_loader import GameOddsLoadError as MlbGameOddsLoadError, unified_game_odds as mlb_unified_game_odds
from modules.mlb_parlay_engine import evaluate_parlay as mlb_evaluate_parlay, make_leg as mlb_make_leg
from modules.mlb_prop_model import evaluate_props as mlb_evaluate_props
from modules.mlb_props_loader import unified_props as mlb_unified_props

from modules.nhl_moneyline_model import evaluate_games as nhl_evaluate_games
from modules.nhl_odds_loader import GameOddsLoadError as NhlGameOddsLoadError, unified_game_odds as nhl_unified_game_odds
from modules.nhl_parlay_engine import evaluate_parlay as nhl_evaluate_parlay, make_leg as nhl_make_leg
from modules.nhl_prop_model import evaluate_props as nhl_evaluate_props
from modules.nhl_props_loader import unified_props as nhl_unified_props

#: CFB and CBB (modules.cfb_prop_model / modules.cbb_prop_model) were built
#: to the exact same row shape as each other (see cbb_prop_model.py's
#: docstring) -- neither has NBA's rich pre-existing projection system to
#: wrap, so both mirror the NFL-style from-scratch Gaussian model
#: directly. This lets Parlays/Player Comparison share one "college
#: sports" rendering path instead of a third and fourth near-duplicate of
#: NFL's or NBA's. Money Lines and Props keep their own per-sport branches
#: below since each has different real-data availability messaging.
COLLEGE_SPORTS = ("CFB", "CBB")
#: MLB and NHL ship no default data (see module docstring) and need no
#: live schedule/team-averages fetch the way CFB/CBB/NBA do -- both share
#: one small "offline" render path below (render_offline_props_tab /
#: render_offline_moneylines_tab) rather than joining COLLEGE_SPORTS,
#: since that path's volatility-caption logic doesn't apply to either.
OFFLINE_SPORTS = ("MLB", "NHL")
MAKE_LEG_BY_SPORT = {"NFL": make_leg, "NBA": nba_make_leg, "CFB": cfb_make_leg, "CBB": cbb_make_leg, "MLB": mlb_make_leg, "NHL": nhl_make_leg}
EVALUATE_PARLAY_BY_SPORT = {
    "NFL": evaluate_parlay, "NBA": nba_evaluate_parlay, "CFB": cfb_evaluate_parlay, "CBB": cbb_evaluate_parlay,
    "MLB": mlb_evaluate_parlay, "NHL": nhl_evaluate_parlay,
}

# =========================================================================
# Cached page-level data loaders
# =========================================================================


@st.cache_data(show_spinner=False, ttl=60 * 60)
def _nfl_players(season: int) -> list[dict[str, Any]]:
    return load_forward_projections(season=season)


@st.cache_data(show_spinner=False, ttl=60 * 60)
def _nfl_team_averages(season: int) -> dict[str, dict[str, float]]:
    return nfl_team_scoring_averages(season)


@st.cache_data(show_spinner=False, ttl=60 * 60)
def _nba_team_averages(season: str) -> dict[str, dict[str, float]]:
    return nba_team_scoring_averages(season)


@st.cache_data(show_spinner=False, ttl=60 * 60)
def nba_volatility(season: str) -> dict[str, float]:
    return real_margin_and_total_volatility(season)


@st.cache_data(show_spinner=False, ttl=15 * 60)
def _nba_todays_games() -> list[dict[str, Any]]:
    return fetch_todays_games()


@st.cache_data(show_spinner=False, ttl=15 * 60)
def _nba_recommendations(season: str, max_players: int) -> list[dict[str, Any]]:
    return nba_recommend_props(min_edge=0.0, min_confidence=0.0, min_reliability=0.0, season=season, max_players=max_players)


@st.cache_data(show_spinner=False, ttl=60 * 60)
def _cfb_team_averages(season: int) -> dict[str, dict[str, float]]:
    return cfb_team_scoring_averages(season)


@st.cache_data(show_spinner=False, ttl=60 * 60)
def cfb_volatility_cached(season: int) -> dict[str, float]:
    return cfb_volatility(season)


@st.cache_data(show_spinner=False, ttl=60 * 60)
def _cfb_week_games(season: int, week: int) -> list[dict[str, Any]]:
    return cfb_fetch_week_games(season, week)


@st.cache_data(show_spinner=False, ttl=15 * 60)
def _cbb_todays_games_cached() -> list[dict[str, Any]]:
    return cbb_todays_games()


@st.cache_data(show_spinner=False, ttl=30 * 60)
def _cbb_team_averages_cached(season: int, team_pool_size: int) -> tuple[dict[str, dict[str, float]], dict[str, list[dict[str, Any]]]]:
    return cbb_build_team_scoring_averages(season, team_pool_size=team_pool_size)


def load_nfl_evaluations(uploader_key: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], dict[str, dict[str, float]]]:
    """Load NFL odds + real players, and return (prop_evaluations, game_evaluations, team_averages)."""
    source_season = upcoming_season() - 1
    with st.expander("Odds source", expanded=True):
        st.caption(
            "Default odds are generated by our own model from real per-game rates and real team scoring -- "
            "not fetched from any sportsbook. Upload a file below to override or add to them; only the "
            "entries your file names are replaced, everything else stays on our default."
        )
        uploaded_file = st.file_uploader(
            "Upload NFL odds (CSV, JSON, or text) to override our defaults",
            type=["csv", "json", "txt"],
            key=uploader_key,
        )
        try:
            odds = unified_odds(uploaded=uploaded_file if uploaded_file is not None else None)
        except OddsLoadError as error:
            st.error(f"Could not parse the uploaded odds file: {error}")
            odds = unified_odds()
        st.success(f"{len(odds['player_props'])} player props · {len(odds['games'])} games loaded.")

    players = _nfl_players(source_season)
    players_by_id = {str(player.get("player_id")): player for player in players}
    team_averages = _nfl_team_averages(source_season)
    prop_evaluations = evaluate_props(players_by_id, odds)
    game_evaluations = evaluate_games(odds, averages=team_averages)
    return prop_evaluations, game_evaluations, team_averages


def load_nba_evaluations(
    props_uploader_key: str, odds_uploader_key: str, *, max_players: int = 20
) -> tuple[list[dict[str, Any]], list[dict[str, Any]], list[dict[str, Any]], dict[str, Any]]:
    """Load NBA odds + real schedule, and return (priced_props, raw_props, game_evaluations, extra_context)."""
    nba_season = nba_latest_season()
    with st.expander("Odds source", expanded=True):
        st.caption(
            "Default NBA prop lines are generated by our own model from real per-game rates (see "
            "modules/nba_props_generator.py) -- not fetched from any sportsbook. Game odds have no fixed "
            "default (NBA's daily schedule changes every day); upload a file below, or rely on our fair "
            "lines alone, computed live from real team scoring."
        )
        uploaded_props_file = st.file_uploader(
            "Upload NBA player props (CSV, JSON, or text) to override our defaults",
            type=["csv", "json", "txt"],
            key=props_uploader_key,
        )
        uploaded_game_odds_file = st.file_uploader(
            "Upload NBA game odds (CSV, JSON, or text) -- moneyline / spread / total",
            type=["csv", "json", "txt"],
            key=odds_uploader_key,
        )

        with st.spinner("Loading odds sources..."):
            try:
                results = parse_uploads_concurrently(
                    {
                        "props": lambda: nba_unified_props(uploaded=uploaded_props_file if uploaded_props_file is not None else None),
                        "game_odds": lambda: unified_game_odds(uploaded=uploaded_game_odds_file if uploaded_game_odds_file is not None else None),
                    }
                )
                nba_props = results["props"]
                nba_game_odds = results["game_odds"]
            except GameOddsLoadError as error:
                st.error(f"Could not parse the uploaded game-odds file: {error}")
                nba_props = nba_unified_props(uploaded=uploaded_props_file if uploaded_props_file is not None else None)
                nba_game_odds = unified_game_odds()
        st.success(f"{len(nba_props)} player props · {len(nba_game_odds['games'])} game odds loaded.")

    todays_games = _nba_todays_games()
    if not todays_games:
        st.info("No real NBA games are scheduled today -- Money Lines and live-matchup Props below will be empty until game day.")

    recommendations: list[dict[str, Any]] = []
    if todays_games:
        with st.spinner("Scanning today's real matchups..."):
            recommendations = _nba_recommendations(nba_season, max_players)
    props_by_key = index_props_by_player_and_category(nba_props)
    priced = price_aware_evaluations(recommendations, props_by_key) if recommendations else []

    game_evaluations: list[dict[str, Any]] = []
    if todays_games:
        nba_averages = _nba_team_averages(nba_season)
        nba_vol = nba_volatility(nba_season)
        odds_by_matchup = index_by_matchup(nba_game_odds)
        game_evaluations = nba_evaluate_games(todays_games, averages=nba_averages, odds_by_matchup=odds_by_matchup, volatility=nba_vol)

    extra = {"season": nba_season, "todays_games": todays_games, "raw_props": nba_props}
    return priced, nba_props, game_evaluations, extra


def load_cfb_evaluations(
    props_uploader_key: str, odds_uploader_key: str, *, season: int, week: int
) -> tuple[list[dict[str, Any]], list[dict[str, Any]], dict[str, Any]]:
    """Load CFB odds, and return (prop_evaluations, game_evaluations, extra_context). Real data needs CFBD_API_KEY."""
    import os

    has_key = bool(os.environ.get("CFBD_API_KEY"))
    with st.expander("Odds source", expanded=True):
        st.caption(
            "Default CFB prop lines need a College Football Data API key (set CFBD_API_KEY -- see "
            "cfb_pipeline.md) -- not fetched from any sportsbook. Upload a file below to use this tab "
            "without a key."
        )
        if not has_key:
            st.warning(
                "No CFBD_API_KEY is configured. Real per-game-rate props and team scoring are empty until "
                "one is set -- this tab still works fully with an uploaded props/odds file."
            )
        uploaded_props_file = st.file_uploader("Upload CFB player props (CSV, JSON, or text)", type=["csv", "json", "txt"], key=props_uploader_key)
        uploaded_game_odds_file = st.file_uploader("Upload CFB game odds (CSV, JSON, or text) -- moneyline / spread / total", type=["csv", "json", "txt"], key=odds_uploader_key)
        cfb_props = cfb_unified_props(uploaded=uploaded_props_file if uploaded_props_file is not None else None)
        try:
            cfb_game_odds = cfb_unified_game_odds(uploaded=uploaded_game_odds_file if uploaded_game_odds_file is not None else None)
        except CfbGameOddsLoadError as error:
            st.error(f"Could not parse the uploaded game-odds file: {error}")
            cfb_game_odds = cfb_unified_game_odds()
        st.success(f"{len(cfb_props)} player props · {len(cfb_game_odds['games'])} game odds loaded.")

    prop_evaluations = cfb_evaluate_props(cfb_props) if cfb_props else []

    games = _cfb_week_games(season, week) if has_key else []
    game_evaluations: list[dict[str, Any]] = []
    if games:
        averages = _cfb_team_averages(season)
        volatility = cfb_volatility_cached(season)
        odds_by_matchup = cfb_index_by_matchup(cfb_game_odds)
        game_evaluations = cfb_evaluate_games(games, averages=averages, odds_by_matchup=odds_by_matchup, volatility=volatility)

    return prop_evaluations, game_evaluations, {"has_key": has_key, "games": games, "raw_props": cfb_props}


def load_cbb_evaluations(
    props_uploader_key: str, odds_uploader_key: str, *, team_pool_size: int = 25
) -> tuple[list[dict[str, Any]], list[dict[str, Any]], dict[str, Any]]:
    """Load CBB odds + real ESPN data, and return (prop_evaluations, game_evaluations, extra_context)."""
    with st.expander("Odds source", expanded=True):
        st.caption(
            "Default CBB prop lines are generated from ESPN's public college-basketball stats API (see "
            "modules/cbb_props_generator.py) -- not fetched from any sportsbook. Game odds have no fixed "
            "default (the daily schedule changes every day); upload a file below, or rely on our fair "
            "lines alone, computed live from real team scoring."
        )
        uploaded_props_file = st.file_uploader("Upload CBB player props (CSV, JSON, or text)", type=["csv", "json", "txt"], key=props_uploader_key)
        uploaded_game_odds_file = st.file_uploader("Upload CBB game odds (CSV, JSON, or text) -- moneyline / spread / total", type=["csv", "json", "txt"], key=odds_uploader_key)
        with st.spinner("Loading odds sources..."):
            try:
                results = parse_uploads_concurrently(
                    {
                        "props": lambda: cbb_unified_props(uploaded=uploaded_props_file if uploaded_props_file is not None else None),
                        "game_odds": lambda: cbb_unified_game_odds(uploaded=uploaded_game_odds_file if uploaded_game_odds_file is not None else None),
                    }
                )
                cbb_props = results["props"]
                cbb_game_odds = results["game_odds"]
            except CbbGameOddsLoadError as error:
                st.error(f"Could not parse the uploaded game-odds file: {error}")
                cbb_props = cbb_unified_props(uploaded=uploaded_props_file if uploaded_props_file is not None else None)
                cbb_game_odds = cbb_unified_game_odds()
        st.success(f"{len(cbb_props)} player props · {len(cbb_game_odds['games'])} game odds loaded.")

    prop_evaluations = cbb_evaluate_props(cbb_props) if cbb_props else []

    games = _cbb_todays_games_cached()
    if not games:
        st.info("No real CBB games are scheduled today -- Money Lines below will be empty until game day.")
    game_evaluations: list[dict[str, Any]] = []
    if games:
        with st.spinner("Loading real team scoring..."):
            averages, games_by_team = _cbb_team_averages_cached(2026, team_pool_size)
        volatility = cbb_volatility(games_by_team)
        odds_by_matchup = cbb_index_by_matchup(cbb_game_odds)
        game_evaluations = cbb_evaluate_games(games, averages=averages, odds_by_matchup=odds_by_matchup, volatility=volatility)

    return prop_evaluations, game_evaluations, {"games": games, "raw_props": cbb_props}


def load_mlb_evaluations(props_uploader_key: str, odds_uploader_key: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], dict[str, Any]]:
    """Load MLB odds, and return (prop_evaluations, game_evaluations, extra_context). Ships empty by design."""
    with st.expander("Odds source", expanded=True):
        st.caption(
            "No live or keyless MLB stats source was integrated this cycle (see mlb_pipeline.md), and this "
            "app never fetches odds from any sportsbook -- upload a props/game-odds file below to use this "
            "page. modules/mlb_season_model.py, the five matchup modules, and modules/mlb_fusion_model.py "
            "are available as an optional richer projection layer even without live data."
        )
        uploaded_props_file = st.file_uploader("Upload MLB player props (CSV, JSON, or text)", type=["csv", "json", "txt"], key=props_uploader_key)
        uploaded_game_odds_file = st.file_uploader("Upload MLB game odds (CSV, JSON, or text) -- moneyline / total", type=["csv", "json", "txt"], key=odds_uploader_key)
        mlb_props = mlb_unified_props(uploaded=uploaded_props_file if uploaded_props_file is not None else None)
        try:
            mlb_game_odds = mlb_unified_game_odds(uploaded=uploaded_game_odds_file if uploaded_game_odds_file is not None else None)
        except MlbGameOddsLoadError as error:
            st.error(f"Could not parse the uploaded game-odds file: {error}")
            mlb_game_odds = mlb_unified_game_odds()
        st.success(f"{len(mlb_props)} player props · {len(mlb_game_odds['games'])} game odds loaded.")

    prop_evaluations = mlb_evaluate_props(mlb_props) if mlb_props else []
    games = list(mlb_game_odds["games"].values())
    game_evaluations = mlb_evaluate_games(games) if games else []
    return prop_evaluations, game_evaluations, {"games": games, "raw_props": mlb_props}


def load_nhl_evaluations(props_uploader_key: str, odds_uploader_key: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], dict[str, Any]]:
    """Load NHL odds, and return (prop_evaluations, game_evaluations, extra_context). Ships empty by design."""
    with st.expander("Odds source", expanded=True):
        st.caption(
            "No live or keyless NHL stats source was integrated this cycle (see nhl_pipeline.md), and this "
            "app never fetches odds from any sportsbook -- upload a props/game-odds file below to use this page."
        )
        uploaded_props_file = st.file_uploader("Upload NHL player props (CSV, JSON, or text)", type=["csv", "json", "txt"], key=props_uploader_key)
        uploaded_game_odds_file = st.file_uploader("Upload NHL game odds (CSV, JSON, or text) -- moneyline / total", type=["csv", "json", "txt"], key=odds_uploader_key)
        nhl_props = nhl_unified_props(uploaded=uploaded_props_file if uploaded_props_file is not None else None)
        try:
            nhl_game_odds = nhl_unified_game_odds(uploaded=uploaded_game_odds_file if uploaded_game_odds_file is not None else None)
        except NhlGameOddsLoadError as error:
            st.error(f"Could not parse the uploaded game-odds file: {error}")
            nhl_game_odds = nhl_unified_game_odds()
        st.success(f"{len(nhl_props)} player props · {len(nhl_game_odds['games'])} game odds loaded.")

    prop_evaluations = nhl_evaluate_props(nhl_props) if nhl_props else []
    games = list(nhl_game_odds["games"].values())
    game_evaluations = nhl_evaluate_games(games) if games else []
    return prop_evaluations, game_evaluations, {"games": games, "raw_props": nhl_props}


# =========================================================================
# Player Props tab renderers
# =========================================================================


def render_nfl_props_tab(prop_evaluations: list[dict[str, Any]]) -> None:
    section_header("Player Props", "Our model's probability of over/under against the loaded odds, ranked by edge.")
    if not prop_evaluations:
        empty_state(
            "No props to evaluate",
            "The loaded odds don't include any player props this pool can price, or none of the "
            "props' players matched a real player. Try uploading a props file.",
            icon="🏈",
        )
        return
    col1, col2, col3 = st.columns(3)
    markets = sorted({row["market"] for row in prop_evaluations})
    market_filter = col1.multiselect("Market", markets, key="props_market_filter")
    risk_filter = col2.multiselect("Risk tier", ["low", "medium", "high"], key="props_risk_filter")
    min_edge = col3.slider("Minimum edge", 0.0, 0.5, 0.0, 0.01, key="props_min_edge")

    filtered = [
        row
        for row in prop_evaluations
        if (not market_filter or row["market"] in market_filter)
        and (not risk_filter or row["risk_tier"] in risk_filter)
        and row["recommended_edge"] >= min_edge
    ]
    st.caption(f"{len(filtered)} of {len(prop_evaluations)} props shown. Click a column header to sort.")
    table = pd.DataFrame(
        [
            {
                "Player": row["name"],
                "Team": row["team"],
                "Market": row["market"],
                "Line": row["line"],
                "Model mean": row["distribution"]["mean"],
                "Side": row["recommended_side"],
                "Model prob.": row[f"model_probability_{row['recommended_side']}"],
                "Fair prob. (odds)": row[f"market_fair_probability_{row['recommended_side']}"],
                "Edge": row["recommended_edge"],
                "EV / $100": row["recommended_ev"],
                "Confidence": row["confidence"],
                "Risk": row["risk_tier"],
                "Odds source": row["odds_source"],
            }
            for row in filtered
        ]
    )
    st.dataframe(
        table,
        width="stretch",
        hide_index=True,
        column_config={
            "Model prob.": st.column_config.NumberColumn(format="%.1%"),
            "Fair prob. (odds)": st.column_config.NumberColumn(format="%.1%"),
            "Edge": st.column_config.NumberColumn(format="%.1%"),
            "EV / $100": st.column_config.NumberColumn(format="%+.2f"),
            "Confidence": st.column_config.NumberColumn(format="%.0%"),
        },
    )


def render_nba_props_tab(priced: list[dict[str, Any]], raw_props: list[dict[str, Any]], season: str) -> None:
    section_header("Player Props", "Our model's probability of over/under against the loaded odds, ranked by edge.")
    if priced:
        col1, col2 = st.columns(2)
        categories = sorted({row["category"] for row in priced})
        category_filter = col1.multiselect("Category", categories, key="nba_props_category_filter")
        min_ev = col2.slider("Minimum |EV| / $100", 0.0, 20.0, 0.0, 0.5, key="nba_props_min_ev")
        filtered = [
            row
            for row in priced
            if (not category_filter or row["category"] in category_filter) and abs(row["recommended_priced_ev"]) >= min_ev
        ]

        show_trends = st.checkbox(
            "Show pace / usage trend overlay (real, cached -- adds a live-derived column per shown row)",
            key="nba_props_show_trends",
        )
        st.caption(f"{len(filtered)} of {len(priced)} priced props shown. Click a column header to sort.")

        rows = []
        for row in filtered:
            entry = {
                "Player": row["player"],
                "Team": row["team"],
                "Category": row["category"],
                "Line": row["sportsbook_line"],
                "Model proj.": row["minutes_adjusted_projection"],
                "Side": row["recommended_priced_side"],
                "Model prob.": row[f"model_probability_{row['recommended_priced_side']}"],
                "Fair prob. (odds)": row[f"market_fair_probability_{row['recommended_priced_side']}"],
                "EV / $100": row["recommended_priced_ev"],
                "Risk": row.get("risk_tier", ""),
                "Reliability": row.get("confidence_score", ""),
            }
            if show_trends:
                try:
                    pace = team_pace_trend(row["team"], season)
                    entry["Pace trend"] = pace["trend"]
                    entry["Pace Δ"] = pace["pace_delta"]
                except Exception:
                    entry["Pace trend"], entry["Pace Δ"] = "n/a", None
                try:
                    usage = player_usage_trend(row["player"], season)
                    entry["Usage trend"] = usage["trend"]
                    entry["Usage Δ (pts)"] = usage["usage_delta"]
                except Exception:
                    entry["Usage trend"], entry["Usage Δ (pts)"] = "n/a", None
            rows.append(entry)

        table = pd.DataFrame(rows)
        st.dataframe(
            table,
            width="stretch",
            hide_index=True,
            column_config={
                "Model prob.": st.column_config.NumberColumn(format="%.1%"),
                "Fair prob. (odds)": st.column_config.NumberColumn(format="%.1%"),
                "EV / $100": st.column_config.NumberColumn(format="%+.2f"),
            },
        )
    else:
        empty_state(
            "No priced props to evaluate",
            "This needs both a real game today (for matchup-adjusted projections) and a loaded prop "
            "line for the same player/category. On a non-game day, browse the raw default lines "
            "below instead.",
            icon="🏀",
        )
        if raw_props:
            st.caption(f"{len(raw_props)} default/uploaded prop lines available (season per-game rates, no live matchup adjustment):")
            st.dataframe(
                pd.DataFrame(
                    [
                        {"Player": row["player_name"], "Team": row["team"], "Category": row["category"], "Line": row["line"], "Basis": row.get("basis", "")}
                        for row in sorted(raw_props, key=lambda r: (r["player_name"], r["category"]))[:200]
                    ]
                ),
                width="stretch",
                hide_index=True,
            )

    with st.expander("Look up a single team/player trend"):
        st.caption("Real season vs. real last-10-games splits from the NBA's own stats API. See modules/nba_trend_signals.py.")
        trend_col1, trend_col2 = st.columns(2)
        team_for_trend = trend_col1.text_input("Team pace trend", "DEN", key="nba_pace_trend_team")
        player_for_trend = trend_col2.text_input("Player usage trend", "Nikola Jokic", key="nba_usage_trend_player")
        if st.button("Check trends", key="nba_trend_check_button"):
            try:
                st.json(team_pace_trend(team_for_trend, season))
            except Exception as error:
                st.warning(f"Could not compute pace trend for {team_for_trend!r}: {error}")
            try:
                st.json(player_usage_trend(player_for_trend, season))
            except Exception as error:
                st.warning(f"Could not compute usage trend for {player_for_trend!r}: {error}")

    with st.expander("Matchup-aware context (real opponent defense, history, injuries, lineup -- see matchup_engine.md)"):
        st.caption(
            "Real opponent-specific game history, real rim/perimeter defensive difficulty, real opponent-injury "
            "context, and real teammate on/off swings for one player against one opponent -- a bounded, disclosed "
            "adjustment, not a full reprojection. See modules/nba_matchup_engine.py."
        )
        mc1, mc2, mc3 = st.columns(3)
        matchup_player = mc1.text_input("Player", "Nikola Jokic", key="nba_matchup_player")
        matchup_team = mc2.text_input("Team", "DEN", key="nba_matchup_team")
        matchup_opponent = mc3.text_input("Opponent", "BOS", key="nba_matchup_opponent")
        matchup_role = st.selectbox("Position role", ["wing", "interior", "primary ball handler"], key="nba_matchup_role")
        if st.button("Compute matchup context", key="nba_matchup_context_button"):
            from modules.nba_matchup_engine import compute_matchup_context

            try:
                with st.spinner("Pulling real opponent-specific signals..."):
                    context = compute_matchup_context(matchup_player, matchup_team, matchup_opponent, season, player_role=matchup_role)
            except Exception as error:
                st.warning(f"Could not compute matchup context: {error}")
            else:
                cm1, cm2, cm3 = st.columns(3)
                cm1.metric("Context multiplier", f"{context['context_multiplier']:.3f}")
                cm2.metric("Difficulty score", f"{context['defense'].get('difficulty_score', 'n/a')}")
                cm3.metric("Real games vs. opponent", context["history"].get("games_sampled", 0))
                if context["opponent_injuries"].get("rim_defender_out"):
                    st.info(f"Real rim defender out: {context['opponent_injuries']['rim_defender_out']['player']}")
                if context["warnings"]:
                    st.caption("Warnings: " + "; ".join(context["warnings"]))
                st.json(context)


def render_college_props_tab(sport: str, priced: list[dict[str, Any]], raw_props: list[dict[str, Any]]) -> None:
    """Shared Props tab for CFB and CBB -- identical row shape (see COLLEGE_SPORTS note above)."""
    section_header("Player Props", "Our model's probability of over/under against the loaded odds, ranked by edge.")
    icon = "🏈" if sport == "CFB" else "🏀"
    if priced:
        col1, col2 = st.columns(2)
        categories = sorted({row["category"] for row in priced})
        category_filter = col1.multiselect("Category", categories, key=f"{sport}_props_category_filter")
        min_edge = col2.slider("Minimum |edge|", 0.0, 0.5, 0.0, 0.01, key=f"{sport}_props_min_edge")
        filtered = [
            row for row in priced
            if (not category_filter or row["category"] in category_filter) and abs(row["recommended_edge"]) >= min_edge
        ]
        st.caption(f"{len(filtered)} of {len(priced)} priced props shown. Click a column header to sort.")
        table = pd.DataFrame(
            [
                {
                    "Player": row["player_name"],
                    "Team": row["team"],
                    "Category": row["category"],
                    "Line": row["line"],
                    "Side": row["recommended_side"],
                    "Model prob.": row[f"model_probability_{row['recommended_side']}"],
                    "Fair prob. (odds)": row[f"market_fair_probability_{row['recommended_side']}"],
                    "Edge": row["recommended_edge"],
                    "EV / $100": row["recommended_ev"],
                    "Risk": row["risk_tier"],
                    "Basis": row.get("basis") or "",
                }
                for row in filtered
            ]
        )
        st.dataframe(
            table,
            width="stretch",
            hide_index=True,
            column_config={
                "Model prob.": st.column_config.NumberColumn(format="%.1%"),
                "Fair prob. (odds)": st.column_config.NumberColumn(format="%.1%"),
                "Edge": st.column_config.NumberColumn(format="%.1%"),
                "EV / $100": st.column_config.NumberColumn(format="%+.2f"),
            },
        )
    else:
        reason = (
            "Set the CFBD_API_KEY environment variable to enable real per-game-rate props, or upload a props file."
            if sport == "CFB"
            else "Upload a props file, or check back after the next default-file regeneration."
        )
        empty_state("No priced props to evaluate", reason, icon=icon)
        if raw_props:
            st.caption(f"{len(raw_props)} default/uploaded prop lines available:")
            st.dataframe(
                pd.DataFrame(
                    [
                        {"Player": row["player_name"], "Team": row["team"], "Category": row["category"], "Line": row["line"], "Basis": row.get("basis", "")}
                        for row in sorted(raw_props, key=lambda r: (r["player_name"], r["category"]))[:200]
                    ]
                ),
                width="stretch",
                hide_index=True,
            )


def render_offline_props_tab(sport: str, priced: list[dict[str, Any]], raw_props: list[dict[str, Any]], *, icon: str) -> None:
    """Shared Props tab for MLB and NHL -- identical row shape, both ship no default data (see OFFLINE_SPORTS)."""
    section_header("Player Props", "Our model's probability of over/under against the loaded odds, ranked by edge.")
    if priced:
        col1, col2 = st.columns(2)
        categories = sorted({row["category"] for row in priced})
        category_filter = col1.multiselect("Category", categories, key=f"{sport}_props_category_filter")
        min_edge = col2.slider("Minimum |edge|", 0.0, 0.5, 0.0, 0.01, key=f"{sport}_props_min_edge")
        filtered = [
            row for row in priced
            if (not category_filter or row["category"] in category_filter) and abs(row["recommended_edge"]) >= min_edge
        ]
        st.caption(f"{len(filtered)} of {len(priced)} priced props shown. Click a column header to sort.")
        table = pd.DataFrame(
            [
                {
                    "Player": row["player_name"],
                    "Team": row["team"],
                    "Category": row["category"],
                    "Line": row["line"],
                    "Side": row["recommended_side"],
                    "Model prob.": row[f"model_probability_{row['recommended_side']}"],
                    "Fair prob. (odds)": row[f"market_fair_probability_{row['recommended_side']}"],
                    "Edge": row["recommended_edge"],
                    "EV / $100": row["recommended_ev"],
                    "Risk": row["risk_tier"],
                    "Basis": row.get("basis") or "",
                }
                for row in filtered
            ]
        )
        st.dataframe(
            table,
            width="stretch",
            hide_index=True,
            column_config={
                "Model prob.": st.column_config.NumberColumn(format="%.1%"),
                "Fair prob. (odds)": st.column_config.NumberColumn(format="%.1%"),
                "Edge": st.column_config.NumberColumn(format="%.1%"),
                "EV / $100": st.column_config.NumberColumn(format="%+.2f"),
            },
        )
    else:
        empty_state("No priced props to evaluate", "Upload a props file to use this tab -- see the Odds source note above.", icon=icon)
        if raw_props:
            st.caption(f"{len(raw_props)} default/uploaded prop lines available:")
            st.dataframe(
                pd.DataFrame(
                    [
                        {"Player": row["player_name"], "Team": row["team"], "Category": row["category"], "Line": row["line"], "Basis": row.get("basis", "")}
                        for row in sorted(raw_props, key=lambda r: (r["player_name"], r["category"]))[:200]
                    ]
                ),
                width="stretch",
                hide_index=True,
            )


# =========================================================================
# Money Lines tab renderers
# =========================================================================


def _game_rows(game_evaluations: list[dict[str, Any]], *, include_ml_side: bool = False, include_total_side: bool = False) -> list[dict[str, Any]]:
    rows = []
    for game in game_evaluations:
        model = game["model"]
        moneyline = game.get("moneyline")
        total = game.get("total")
        row = {
            "Home": game["home_team"],
            "Away": game["away_team"],
            "Model spread (home)": model["spread"],
            "Model total": model["total"],
            "Home win prob.": model["home_win_probability"],
            "Fair home ML": model["fair_home_moneyline"],
            "Market home ML": moneyline["home_price"] if moneyline else None,
            "ML edge": moneyline["recommended_edge"] if moneyline else None,
        }
        if include_ml_side:
            row["ML side"] = moneyline["recommended_side"] if moneyline else None
        row["Total line"] = total["line"] if total else None
        row["Total edge"] = total["recommended_edge"] if total else None
        if include_total_side:
            row["Total side"] = total["recommended_side"] if total else None
        rows.append(row)
    return rows


def render_nfl_moneylines_tab(game_evaluations: list[dict[str, Any]]) -> None:
    section_header("Money Lines", "Fair spread, total, and moneyline from real team scoring this season, compared to the loaded odds.")
    if not game_evaluations:
        empty_state(
            "No games to evaluate",
            "The loaded odds don't include any game lines. Upload a game-odds file (home_team, "
            "away_team, moneyline_home, moneyline_away, total_line, ...) to populate this tab.",
            icon="🏟️",
        )
        return
    rows = _game_rows(game_evaluations, include_ml_side=True, include_total_side=True)
    table = pd.DataFrame(rows).sort_values(by=[c for c in ("ML edge", "Total edge") if True], ascending=False, na_position="last")
    st.caption("Click a column header to sort.")
    st.dataframe(
        table,
        width="stretch",
        hide_index=True,
        column_config={
            "Home win prob.": st.column_config.NumberColumn(format="%.1%"),
            "ML edge": st.column_config.NumberColumn(format="%.1%"),
            "Total edge": st.column_config.NumberColumn(format="%.1%"),
        },
    )


def render_nba_moneylines_tab(todays_games: list[dict[str, Any]], game_evaluations: list[dict[str, Any]], season: str) -> None:
    section_header("Money Lines", "Fair spread, total, and moneyline from real team scoring this season, compared to the loaded odds.")
    if not todays_games:
        empty_state(
            "No NBA games today",
            "Money lines are evaluated for today's real schedule only -- there is nothing to price "
            "when no games are on. Check back on a game day.",
            icon="🏀",
        )
        return
    rows = _game_rows(game_evaluations)
    table = pd.DataFrame(rows).sort_values(by=[c for c in ("ML edge", "Total edge") if True], ascending=False, na_position="last")
    vol = nba_volatility(season)
    st.caption(f"Margin volatility: {vol['margin_stdev']} pts, total volatility: {vol['total_stdev']} pts ({vol['basis']}). Click a column header to sort.")
    st.dataframe(
        table,
        width="stretch",
        hide_index=True,
        column_config={
            "Home win prob.": st.column_config.NumberColumn(format="%.1%"),
            "ML edge": st.column_config.NumberColumn(format="%.1%"),
            "Total edge": st.column_config.NumberColumn(format="%.1%"),
        },
    )


def render_college_moneylines_tab(sport: str, game_evaluations: list[dict[str, Any]], extra: dict[str, Any]) -> None:
    """Shared Money Lines tab for CFB and CBB."""
    section_header("Money Lines", "Fair spread, total, and moneyline from real team scoring this season, compared to the loaded odds.")
    icon = "🏈" if sport == "CFB" else "🏀"
    if sport == "CFB" and not extra["has_key"]:
        empty_state("No CFBD_API_KEY configured", "Real CFB team scoring and schedule need a College Football Data API key -- see cfb_pipeline.md.", icon=icon)
        return
    if not game_evaluations:
        reason = "No games found for that season/week -- try another week." if sport == "CFB" else "No real games are scheduled today -- check back on a game day."
        empty_state("No games to evaluate", reason, icon=icon)
        return
    rows = _game_rows(game_evaluations)
    table = pd.DataFrame(rows).sort_values(by=[c for c in ("ML edge", "Total edge") if True], ascending=False, na_position="last")
    volatility = cfb_volatility_cached(int(extra["season"])) if sport == "CFB" else cbb_volatility(extra.get("games_by_team", {}))
    st.caption(f"Margin volatility: {volatility['margin_stdev']} pts, total volatility: {volatility['total_stdev']} pts ({volatility['basis']}). Click a column header to sort.")
    st.dataframe(
        table,
        width="stretch",
        hide_index=True,
        column_config={
            "Home win prob.": st.column_config.NumberColumn(format="%.1%"),
            "ML edge": st.column_config.NumberColumn(format="%.1%"),
            "Total edge": st.column_config.NumberColumn(format="%.1%"),
        },
    )


def render_offline_moneylines_tab(sport: str, game_evaluations: list[dict[str, Any]], *, icon: str) -> None:
    """Shared Money Lines tab for MLB and NHL -- moneyline only (no run line/puck line, no total this cycle;
    see OFFLINE_SPORTS and modules/mlb_moneyline_model.py / modules/nhl_moneyline_model.py)."""
    section_header("Money Lines", "Fair moneyline from caller-supplied team context, compared to the loaded odds.")
    if not game_evaluations:
        empty_state(
            "No games to evaluate",
            "Upload a game-odds file with at least a home_team/away_team/moneyline_home/moneyline_away row "
            "to populate this tab -- see the Odds source note above.",
            icon=icon,
        )
        return
    rows = []
    for game in game_evaluations:
        model = game["model"]
        moneyline = game.get("moneyline")
        rows.append(
            {
                "Home": game["home_team"],
                "Away": game["away_team"],
                "Home win prob.": model["home_win_probability"],
                "Fair home ML": model["fair_home_moneyline"],
                "Market home ML": moneyline["home_price"] if moneyline else None,
                "ML side": moneyline["recommended_side"] if moneyline else None,
                "ML edge": moneyline["recommended_edge"] if moneyline else None,
            }
        )
    table = pd.DataFrame(rows).sort_values(by="ML edge", ascending=False, na_position="last")
    st.caption(
        "Team context (pitcher/bullpen/park/defense/lineup for MLB, goaltending/offense/defense/special-teams "
        "for NHL) defaults to neutral unless supplied by a future caller. Click a column header to sort."
    )
    st.dataframe(
        table,
        width="stretch",
        hide_index=True,
        column_config={
            "Home win prob.": st.column_config.NumberColumn(format="%.1%"),
            "ML edge": st.column_config.NumberColumn(format="%.1%"),
        },
    )


# =========================================================================
# Parlays tab (shared builder for all six sports)
# =========================================================================


def render_parlay_builder(*, prop_evaluations: list[dict[str, Any]], sport_key: str, empty_icon: str) -> None:
    """Shared parlay-builder UX for one sport: quick-add top edges, leg summary, evaluation. Same UX for all six sports."""
    section_header("Parlays", "Build a parlay from the props above -- correlation-adjusted hit probability, EV, and risk.")
    make_leg_fn = MAKE_LEG_BY_SPORT[sport_key]
    evaluate_parlay_fn = EVALUATE_PARLAY_BY_SPORT[sport_key]

    if sport_key == "NFL":
        options = {f"{row['name']} {row['market']} {row['recommended_side']} {row['line']}": row for row in prop_evaluations}
        side_key, edge_key = "recommended_side", "recommended_edge"
    elif sport_key == "NBA":
        options = {f"{row['player']} {row['category']} {row['recommended_priced_side']} {row['sportsbook_line']}": row for row in prop_evaluations}
        side_key, edge_key = "recommended_priced_side", "recommended_priced_ev"
    else:
        options = {f"{row['player_name']} {row['category']} {row['recommended_side']} {row['line']}": row for row in prop_evaluations}
        side_key, edge_key = "recommended_side", "recommended_edge"

    if len(options) < 2:
        empty_state("Not enough props loaded to build a parlay", "A parlay needs at least two legs -- load more props first.", icon=empty_icon)
        return

    ranked_labels = sorted(options, key=lambda label: -abs(options[label][edge_key]))
    picker_key = f"{sport_key}_parlay_leg_picker"
    # Streamlit forbids passing both `default=` and pre-setting session_state
    # for the same widget key -- seed/reseed session_state here instead and
    # let the widget read purely from it (see ui_design.md).
    stored = st.session_state.get(picker_key)
    if stored is None or any(label not in options for label in stored):
        st.session_state[picker_key] = ranked_labels[: min(3, len(options))]

    quick_add_col, _ = st.columns([1, 3])
    quick_add_n = quick_add_col.number_input("Quick-add top N by edge", min_value=2, max_value=min(8, len(options)), value=min(3, len(options)), key=f"{sport_key}_quick_add_n")
    if quick_add_col.button("Quick-add", key=f"{sport_key}_quick_add_button"):
        st.session_state[picker_key] = ranked_labels[:quick_add_n]

    chosen_labels = st.multiselect(
        "Legs",
        list(options),
        key=picker_key,
        help="Each leg uses the model's recommended side and its own price from the loaded odds.",
    )
    if len(chosen_labels) < 2:
        st.info("Pick at least 2 legs to evaluate a parlay.")
        return

    summary_rows = []
    legs = []
    for label in chosen_labels:
        row = options[label]
        side = row[side_key]
        if sport_key == "NFL":
            leg = make_leg_fn(
                description=label, model_probability=row[f"model_probability_{side}"], price=row[f"{side}_price"],
                player_id=row["player_id"], team=row["team"], market=row["market"], side=side, confidence=row["confidence"],
            )
            summary_rows.append({"Leg": label, "Model prob.": row[f"model_probability_{side}"], "Edge": row["recommended_edge"], "Risk": row.get("risk_tier", "")})
        elif sport_key == "NBA":
            leg = make_leg_fn(
                description=label, model_probability=row[f"model_probability_{side}"], price=row[f"{side}_price"],
                player_id=row["player"], team=row["team"], market=row["category"], side=side, confidence=row.get("confidence_score", 70.0) / 100.0,
            )
            summary_rows.append({"Leg": label, "Model prob.": row[f"model_probability_{side}"], "EV / $100": row["recommended_priced_ev"], "Risk": row.get("risk_tier", "")})
        else:
            confidence = {"low": 0.8, "medium": 0.5, "high": 0.25}.get(row.get("risk_tier"), 0.6)
            leg = make_leg_fn(
                description=label, model_probability=row[f"model_probability_{side}"], price=row[f"{side}_price"],
                player_id=row.get("player_name"), team=row["team"], market=row["category"], side=side, confidence=confidence,
            )
            summary_rows.append({"Leg": label, "Model prob.": row[f"model_probability_{side}"], "EV / $100": row["recommended_ev"], "Risk": row.get("risk_tier", "")})
        legs.append(leg)

    st.dataframe(pd.DataFrame(summary_rows), width="stretch", hide_index=True, column_config={"Model prob.": st.column_config.NumberColumn(format="%.1%")})

    result = evaluate_parlay_fn(legs)
    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Adjusted hit probability", f"{result['adjusted_hit_probability']:.1%}")
    m2.metric("Payout / $100", f"${result['payout_per_100_stake']:,.2f}")
    m3.metric("Adjusted EV / $100", f"${result['adjusted_ev']:+,.2f}")
    m4.metric("Confidence", f"{result['confidence']:.0%}", help=f"Risk tier: {result['risk_tier']}")

    if result["correlations_detected"]:
        st.warning(f"Correlated legs detected -- hit probability adjusted from the naive {result['naive_hit_probability']:.1%} to {result['adjusted_hit_probability']:.1%}.")
        for finding in result["correlations_detected"]:
            leg_a, leg_b = finding["legs"]
            st.caption(f"- {legs[leg_a]['description']} + {legs[leg_b]['description']}: {finding['note']}")
    else:
        st.caption("No known correlation pattern detected between these legs.")
