"""Public package for the unified fantasy Quant Engine.

The package root intentionally re-exports only the stable facade and loader
contracts.  Specialized engines are imported lazily by :mod:`quant_engine`,
which keeps ``import quant`` safe even when an application initializes modules
in a different order.
"""

from .data_loader import (
    CANONICAL_PLAYER_SCHEMA,
    DataLoadError,
    canonical_player_schema,
    load_adp_feeds,
    load_all_player_data,
    load_depth_charts,
    load_historical_data,
    load_injury_data,
    load_news_signals,
    load_player_stats,
    load_schedule_data,
    load_team_strength,
    load_weather_data,
    normalize_player_record,
)
from .quant_engine import (
    QuantEngine,
    compute_base_projections,
    compute_breakout_probability,
    compute_bust_probability,
    compute_confidence_scores,
    compute_draft_value,
    compute_efficiency_scores,
    compute_final_projection,
    compute_health_adjustments,
    compute_momentum,
    compute_player_similarity,
    compute_positional_scarcity,
    compute_rarity_tier,
    compute_trade_value,
    compute_trend_lines,
    compute_usage_rates,
    compute_value_over_replacement,
    compute_volatility,
    compute_weekly_matchup_score,
    default_engine,
    quant,
)

__all__ = [
    "CANONICAL_PLAYER_SCHEMA",
    "DataLoadError",
    "QuantEngine",
    "canonical_player_schema",
    "compute_base_projections",
    "compute_breakout_probability",
    "compute_bust_probability",
    "compute_confidence_scores",
    "compute_draft_value",
    "compute_efficiency_scores",
    "compute_final_projection",
    "compute_health_adjustments",
    "compute_momentum",
    "compute_player_similarity",
    "compute_positional_scarcity",
    "compute_rarity_tier",
    "compute_trade_value",
    "compute_trend_lines",
    "compute_usage_rates",
    "compute_value_over_replacement",
    "compute_volatility",
    "compute_weekly_matchup_score",
    "default_engine",
    "load_adp_feeds",
    "load_all_player_data",
    "load_depth_charts",
    "load_historical_data",
    "load_injury_data",
    "load_news_signals",
    "load_player_stats",
    "load_schedule_data",
    "load_team_strength",
    "load_weather_data",
    "normalize_player_record",
    "quant",
]
